### ISSUE TITLE
Crash upon startup (superblocks mod) [1.12.2]

### ISSUE THREAD

**Issue by varappdev** [Wabbit0101/mods_hoardercraft#101]
So, I do not know but when I installed super blocks my game decided to do not start up and crash. VanillaFix said it is because of this mod and generated this crash report: https://paste.dimdev.org/iyemavibal.mccrash
And also debug.log: [debug.log](https://github.com/Wabbit0101/mods_hoardercraft/files/4417112/debug.log)

PLEASE do not tell me it's from the quark slime blocks again.

**Comment by Wabbit0101** [comment]
It's the same problem. Not sure what to tell you -- **those mods use the same underlying library** which has this check.  If you don't need Quark to replace slime blocks (for bouncing items off the blocks...no less), then you can disable that feature and things work. 

As I summarized before, if another mod subsitutes its own blocks for vanilla blocks, the current  1.12 version of these vanilla-assuming mods will have issues (they can either break or create lots of lovely dup bugs in their recipes...I picked breaking so the modpack author like yourself knows there is an issue and can remove my mod or workaround it.) 

As 1.12 development is stopped for these mods, just remove Superblocks if you don't want to change Quark's config. There are many other mods that do block compression that work fine so you should be good to go with one of those...
