### ISSUE TITLE
[1.15.2]Console error

### ISSUE THREAD

**Issue by EnterFor** [Wabbit0101/mods_hoardercraft#102]
![image](https://user-images.githubusercontent.com/10114685/78331119-f9490a80-75b7-11ea-8664-35c2049fd751.png)
Forge：31.1.35
Mod：5.5b

**Comment by Wabbit0101** [comment]
This has been fixed. You'll see in the next beta (probably some time next week - Apr9/Apr10). thanks for report and screen shot.
