### ISSUE TITLE
[1.15.2-5.5b1] Burnt meat unobtainable?

### ISSUE THREAD

**Issue by Rictu5** [Wabbit0101/mods_hoardercraft#103]
I can't seem to find the recipe for burnt meat (guardian or bear), JEI is not helping.
Tried campfire cooking with no avail.

forge : 31.1.27

**Comment by Wabbit0101** [comment]
Burnt meat is what is dropped when a mob (passive or otherwise) dies while on fire. You can trigger this by using Fire Aspect or a killing chamber w/ burning netherrack.
