### ISSUE TITLE
Apple Juice crash 1.15.2

### ISSUE THREAD

**Issue by Zentraxius** [Wabbit0101/mods_hoardercraft#104]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/9/20 8:22 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:214)

-- Item being rendered --
Details:
	Item Type: juice_apple
	Registry Name: vanillafoodpantry:juice_apple
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:214)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:37)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:26)
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:178)
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:154)
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:154)
	at mezz.jei.gui.recipes.RecipesGui.render(RecipesGui.java:224)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$453/1458751976.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- Ingredient being rendered --
Details:
	Mod Name: Vanilla Food Pantry
	Registry Name: vanillafoodpantry:juice_apple
	Display Name: Apple Cider
	String Name: 1 juice_apple

-- JEI render details --
Details:
	Unique Id (for Blacklist): vanillafoodpantry:juice_apple
	Ingredient Type: class net.minecraft.item.ItemStack
	Error Info: 1 juice_apple vanillafoodpantry:juice_apple
	Filter Text: @aqua
	Edit Mode Enabled: false
	Debug Mode Enabled: false

-- Screen render details --
Details:
	Screen name: mezz.jei.gui.recipes.RecipesGui
	Mouse location: Scaled: (515, 90). Absolute: (1546.000000, 270.000000)
	Screen size: Scaled: (854, 455). Absolute: (2560, 1363). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['LimeySkull'/37805, l='MpServer', x=-407.58, y=68.00, z=-150.97], RemoteClientPlayerEntity['Zentraxius'/777, l='MpServer', x=-430.58, y=62.08, z=-146.13]]
	Chunk stats: Client Chunk Cache: 625, 423
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 7295776630195683379
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-128,66,112), Chunk: (at 0,4,0 in -8,7; contains blocks -128,0,112 to -113,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 144014 game time, 175204 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1476074160 bytes (1407 MB) / 7646740480 bytes (7292 MB) up to 8601468928 bytes (8203 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9228m -Xms2256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.36
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.0
		kotori_scala@2.13.1-build-6
	Mod List: 
		tetra-1.15.2-2.0.1.jar Tetra {tetra@1.15.2-2.0.1 DONE}
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 DONE}
		DeathCounter-1.15.2-1.2.0.jar Death Counter {deathcounter@1.2.0 DONE}
		prefab-1.5.0.3.jar Prefab {prefab@1.5.0.3 DONE}
		extrabows-v1.15.2 b1.jar Extra Bows {extrabows@v1.15.2 b1 DONE}
		ProjectE-1.15.2-PE1.0.3B.jar ProjectE {projecte@1.0.3B DONE}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		rsgauges-1.15.2-1.2.2.jar Gauges and Switches {rsgauges@1.2.2 DONE}
		IronJetpacks-1.15.2-3.0.1.jar Iron Jetpacks {ironjetpacks@3.0.1 DONE}
		essentials-1.15.2-2.7.0.jar Essentials {essentials@1.15.2-2.7.0 DONE}
		ForgeEndertech-1.15.2-6.0.1.0-build.0011.jar Forge Endertech {forgeendertech@6.0.1.0 DONE}
		JRFTL [1.15.2]-1.1.jar JRFTL {jrftl@1.1 DONE}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 DONE}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		dankstorage-2.6.jar Dank Storage {dankstorage@2.6 DONE}
		NoFog-1.15b1.jar NoFog {nofog@1.0.1 DONE}
		Powah-1.15.2-1.1.12.jar Powah {powah@1.1.12 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		NomadicTents-1.15.2-11.0.0-beta.jar Nomadic Tents {nomadictents@11.0.0-beta DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		MutantBeasts-1.15.2-1.0.4.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.4 DONE}
		Bookshelf-1.15.2-5.3.9.jar Bookshelf {bookshelf@5.3.9 DONE}
		Reliquary-1.15.2-1.3.4.960.jar Reliquary {xreliquary@1.15.2-1.3.4.960 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 DONE}
		buildinggadgets-3.3.4.jar Building Gadgets {buildinggadgets@3.3.4 DONE}
		DarkUtilities-1.15.2-3.0.2.jar Dark Utilities {darkutils@3.0.2 DONE}
		Apotheosis-1.15.2-3.0.7.jar Apotheosis {apotheosis@3.0.7 DONE}
		LightingWand-1.15.2-1.4.2.jar Lighting Wand {lightingwand@1.4.2 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.9.18.410.jar Mekanism: Generators {mekanismgenerators@9.9.18 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		absentbydesign-1.15.2-1.0.5 .jar Absent By Design Mod {absentbydesign@1.15.2-1.0.5  DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		extendedfurnace-2.2.jar Extended Furnace {extendedfurnace@2.2 DONE}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 DONE}
		anviltweaks-2.2a.jar Anvil Tweaks {anviltweaks@2.2a DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		Overloaded Compressed Blocks-1.15.2-1.0.12.jar Overloaded Compressed Blocks {overloaded_cb@1.15.2-1.0.10 DONE}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		Lollipop-1.15.2-1.0.14.jar Lollipop {lollipop@1.0.14 DONE}
		ironfurnaces-1.15.2-2.0.1.jar Iron Furnaces {ironfurnaces@2.0.1 DONE}
		SilentGear-1.15.2-1.5.6+81.jar Silent Gear {silentgear@1.5.6+81 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		RaysDongles-4.2.2b.jar Ray's Dongles {slurpiesdongles@4.2.2b DONE}
		simplybackpacks-1.15.2-1.4.5.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.5 DONE}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		curios-FORGE-1.15.2-2.0.2.1.jar Curios API {curios@FORGE-1.15.2-2.0.2.1 DONE}
		Botania r1.15-382.jar Botania {botania@r1.15-382 DONE}
		Patchouli-1.15.2-1.2-30.jar Patchouli {patchouli@1.15.2-1.2-30 DONE}
		carrotslib-mc1.15.2-2.5b1.jar Carrots Lib {carrots@2.5.0b1 DONE}
		vanillafoodpantry-mc1.15.2-5.5b1.jar Vanilla Food Pantry {vanillafoodpantry@5.5.0b1 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		tombstone-4.3.3-1.15.2.jar Corail Tombstone {tombstone@4.3.3 DONE}
		obfuscate-0.4.1-1.15.2.jar Obfuscate {obfuscate@0.4.1 DONE}
		vehicle-mod-0.43.5-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.5 DONE}
		ProjectExtended-1.15.2-1.1.0.jar ProjectExtended {projectextended@1.1.0 DONE}
		noRecipeBook_v1.5.2formc1.15.2.jar No Recipe Book {norecipebook@1.5.2 DONE}
		NaturesAura-23.5.jar Nature's Aura {naturesaura@version DONE}
		MekanismTools-1.15.2-9.9.18.410.jar Mekanism: Tools {mekanismtools@9.9.18 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 DONE}
		AdChimneys-1.15.2-5.0.3.0-build.0015.jar Advanced Chimneys {adchimneys@5.0.3.0 DONE}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		SimpleDiscordRichPresence-1.15.2-1.2.6.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.6 DONE}
		QuantumStorage-1.15.2-5.1.1.jar QuantumStorage {quantumstorage@NONE DONE}
		TrinityWeapons-1.15.2-1.4.1.jar TrinityWeapons {trinity@1.4.1 DONE}
		Cyclic-1.15.2-0.3.2.jar Cyclic {cyclic@1.15.2-0.3.2 DONE}
		SaveMyStronghold-1.15.2-1.0.0.jar Save My Stronghold! {savemystronghold@1.15.2-1.0.0 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		Cucumber-1.15.2-3.0.4.jar Cucumber Library {cucumber@3.0.4 DONE}
		EquipmentTooltips-1.15.2-1.4.0+11.jar Equipment Tooltips {equipmenttooltips@1.4.0+11 DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		craftingstation-3.1.0.jar Crafting Station {craftingstation@3.1.0 DONE}
		Overloaded-1.15.2-0.0.86.jar Overloaded {overloaded@1.15.2-0.0.84 DONE}
		Mine and Slash-1.15.2-3.5.1.jar Mine and Slash {mmorpg@3.5.1 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.9.18.410.jar Mekanism {mekanism@9.9.18 DONE}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 DONE}
		colytra-FORGE-1.15.2-3.0.jar Colytra {colytra@FORGE-1.15.2-3.0 DONE}
		invtweaks-1.15.2-1.0.3.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.3 DONE}
		MS Auto-Compat-1.15.2-1.2.0.jar M&S Auto-Compat 1.15.1 {azurecompat@1.2.0 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		mgui-1.15.2-2.0.1.jar mgui {mgui@2.0.1 DONE}
		LightOverlay-4.3.jar Light Overlay Forge {lightoverlay-forge@4.3 DONE}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		enviromats-1.15.2-2.0.2.1.jar Environmental Materials {enviromats@1.15.2-2.0.2.1 DONE}
		comforts-FORGE-1.15.2-2.0.jar Comforts {comforts@FORGE-1.15.2-2.0 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		good-nights-sleep-1.15.2-1.0.3.jar Good Night's Sleep {goodnightsleep@1.0.3 DONE}
		EnderBags-1.15.1-5.0.0.jar Ender Bags {ender_bags@5.0.0 DONE}
		SimpleStorageNetwork-1.15.2-0.3.2.jar Simple Storage Network {storagenetwork@1.15.2-0.3.2 DONE}
		BasicNetherOres-1.15.2-4.0.0.jar Basic Nether Ores {bno@4.0.0 DONE}
		VanillaTweaks-1.15.2.1.5.20.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.20 DONE}
		AdHooks-1.15.2-5.0.0.0-build.0004.jar Advanced Hook Launchers {adhooks@5.0.0.0 DONE}
		engineerstools-1.15.2-1.0.6.jar Engineer's Tools {engineerstools@1.0.6 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		alib-1.15.2-1.jar A Lib {alib@1.15.2-1 DONE}
		mcjtylib-1.15-4.0.3-alpha.jar McJtyLib {mcjtylib@1.15-4.0.3-alpha DONE}
		rftoolsbase-1.15-1.0.1-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.1-alpha DONE}
		xnet-1.15-2.0.2-alpha.jar XNet {xnet@1.15-2.0.2-alpha DONE}
		rftoolsstorage-1.15-1.0.3-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.3-alpha DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		thutessentials-1.15.2-3.0.10.jar Thut Essentials {thutessentials@3.0.10 DONE}
		PackingTape-1.15.2-0.9.5.jar Packing Tape {packingtape@0.9.5 DONE}
		CraftTweaker-1.15.2-6.0.0.10.jar CraftTweaker {crafttweaker@6.0.0.10 DONE}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		forge-1.15.2-31.1.36-universal.jar Forge {forge@31.1.36 DONE}
		Bountiful-1.15.2-3.1.0.jar Bountiful {bountiful@1.15.2-3.1.0 DONE}
		exp_bottling-1.15.2-1.jar EXP Bottling {exp_bottling@1.15.2-1 DONE}
		MysticalAgriculture-1.15.2-3.0.1.jar Mystical Agriculture {mysticalagriculture@3.0.1 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		SimpleDivingGear-4.0.1 mc 1.15.2.jar Simple Diving Gear {simpledivegear@4.0.1 mc 1.15.2 DONE}
		forge-1.15.2-31.1.36-client.jar Minecraft {minecraft@1.15.2 DONE}
		rftoolsutility-1.15-2.0.1-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.1-alpha DONE}
		itlt-1.15.2-1.0.2.jar It's the little things {itlt@1.15.2-1.0.2 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		playerplates-1.15-forge-1.0.0.jar Player Plates {playerplates@1.15-forge-1.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		CreativeCore_v2.0.5_mc1.15.2.jar CreativeCore {creativecore@2.0.0 DONE}
		forbidden_arcanus-1.15.2-1.1.jar Forbidden & Arcanus {forbidden_arcanus@1.15.1-1.0-beta-1 DONE}
		AdLods-1.15.2-3.0.1.0-build.0008.jar Large Ore Deposits {adlods@3.0.1.0 DONE}
		SoulShardsRespawn-forge-1.15.2-1.2.0-15.jar Soul Shards Respawn {soulshards@version DONE}
		LargeFluidTank-15.2.3.jar FluidTank {fluidtank@15.2.3 DONE}
		rftoolsbuilder-1.15-2.0.1-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.1-alpha DONE}
		paintings-1.15.2-7.0.0.0.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE}
		extragolems-10.1.0.jar Extra Golems {golems@10.1.0 DONE}
		flux-4.13.0.jar Flux {flux@4.13.0 DONE}
		fl-3.2.0.jar Flux Library {fl@3.2.0 DONE}
		extratags-1.0.jar Extra Tags {extratags@1.0 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-230.jar Quark {quark@r2.1-230 DONE}
		Charm-1.15.2-1.5.4.jar Charm {charm@1.15.2-1.5.4 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		themidnight-0.5.4.jar The Midnight {midnight@0.5.4 DONE}
		tubesreloaded-1.15.2-1.3.0c.jar Tubes Reloaded {tubesreloaded@1.15.2-1.3.0c DONE}
		structurize-0.10.296-ALPHA.jar Structurize {structurize@0.10.296-ALPHA DONE}
		PickleTweaks-1.15.2-4.0.1.jar Pickle Tweaks {pickletweaks@4.0.1 DONE}
		minecolonies-0.11.810-BETA-universal.jar Minecolonies {minecolonies@0.11.810-BETA DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Vampirism-1.15.2-1.6.0-alpha+20200329-0140.jar Vampirism {vampirism@1.6.0-alpha+20200329-0137 DONE, teamlapenlib@1.6.0-alpha+20200329-0137 DONE}
		mobcatcher-2.2.jar Mob Catcher {mobcatcher@2.2 DONE}
		engineersdecor-1.15.2-1.0.20-b4.jar Engineer's Decor {engineersdecor@1.0.20-b4 DONE}
		RefinedRelocation_1.15.2-7.1.0.jar Refined Relocation {refinedrelocation@7.1.0 DONE}
		solcarrot-1.15.2-1.9.4.jar Spice of Life: Carrot Edition {solcarrot@1.15.2-1.9.4 DONE}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 DONE}
		SilentGems-1.15.2-3.5.1+84.jar Silent's Gems 3 {silentgems@3.5.1+84 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		CosmeticArmorReworked-1.15.2-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v1a DONE}
		thutcore-1.15.2-7.0.3.jar Thut Core {thutcore@7.0.3 DONE, thutcrafts@7.0.3 DONE}
		xptome-1.15.1-v1.1.4.jar XP Tome {xpbook@v1.1.4 DONE}
		farlanders-1.15.2-1.1.2.jar The Farlanders {farlanders@1.1.2 DONE}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 DONE}
	Launched Version: forge-31.1.36
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz

**Comment by Zentraxius** [comment]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:256)

-- Ingredient being rendered --
Details:
	Mod Name: Vanilla Food Pantry
	Registry Name: vanillafoodpantry:juice_apple
	Display Name: Apple Cider
	String Name: 1 juice_apple
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:256)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:31)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:175)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:107)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:113)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:177)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:82)
	at net.minecraftforge.eventbus.ASMEventHandler_1980_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:369)
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:363)
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.render(SourceFile:82)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$453/1458751976.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)


Same crash from different client/user

**Comment by Wabbit0101** [comment]
This is an error inside the JEI mod, not Vanilla Food Pantry. Ping that mod's author. Check the stacktrace you've supplied --
`Thread: Render thread
Stacktrace:
at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:256)`
