### ISSUE TITLE
Crashes game at start

### ISSUE THREAD

**Issue by Frankencraft** [Wabbit0101/mods_hoardercraft#106]
https://paste.dimdev.org/ijilisuhan.mccrash heres the crash report. simply forge detected that this mod was the problem for starting up the game. I have no other option but to remove it, hopefully It can be fixed

**Comment by Wabbit0101** [comment]
Um...you're running out of block ids. Has nothing to do with this mod specifically as it's a limit within Minecraft 1.12 and earlier. If you doing a modpack, I strongly recommend adding a mod that can extend your block ids count in MC-1.12. This limitation was the driving change behind Minecraft 1.13 rewrite by Mojang (Minecraft 1.13+ now has a limit of millions of block ids).
