### ISSUE TITLE
Bits o' Lava Sand turn into Blaze Powder upon crafting

### ISSUE THREAD

**Issue by CircusSeal** [Wabbit0101/mods_hoardercraft#108]
I'm in 1.12.2, and I crafted some Bits o' Lava Sand, only for them to immediately transform into Blaze Powder. I wonder if it has something to do with the fact that I have Unifier.

**Comment by Wabbit0101** [comment]
The lava sand is put under the ore dict "dustLava"...it might be unifying that or maybe some other mod looking for anything that makes blazerods (?) You can use JEI to check **$dustLava** to see if lava sand and blaze powder are matching.

**Comment by CircusSeal** [comment]
Phew! Okay, I deleted "dust" under the things unifier is allowed to, well, unify. It worked perfectly. Thank you!

(Also, thank you very much for your patience with me, lol. I know I ask a lot of questions since I don't know jack squat about computer stuff. Thank you for answering all my potentially-dumb questions. :)

**Comment by Wabbit0101** [comment]
As you were able to resolve issue on your side, I'll mark this closed.
