### ISSUE TITLE
No recipe for Jar of Veggie Stock

### ISSUE THREAD

**Issue by Angela** [Wabbit0101/mods_hoardercraft#109]
I'm playing Vanilla Food Pantry (vanillafoodpantry-mc1.15.2-5.5.jar), following the advancements and as far as I can tell there is no recipe for Jar of Veggie Stock as required for the advancement "Now You're Cooking!"

**Comment by Wabbit0101** [comment]
You're right. The alternate vanilla-ingredient only recipe is disabled by mistake. I will fix. In the meantime, if you're playing with other mods that add crops (celery, onion, garlic) you should be able to get a recipe (update this comment w/ what mods you have).

**Comment by Angela** [comment]
I'm not playing with any mods that add significant numbers of crops, so that would explain it. Mod list included below for completeness though:

    Waddles (by Girafi)
    Cosmetic Armor Reworked (by LainMI)
    Rare Ice (Forge/Fabric) (by shedaniel)
    Absent by Design (by Lothrazar)
    Colorful Slimes (by Zeitheron)
    Wallpapercraft - A Fresh Roll (by Ommina_)
    Vanilla Hammers [Forge] (by MelanX)
    Bamboo Blocks (by bageldotjpg)
    Buzzier Bees (by bageldotjpg)
    🥝 Kiwi (by Snownee_)
    Hammer (Lib) Core (by Zeitheron)
    CoFH Core (by TeamCoFH)
    Shulker Drops Two (by Serilum)
    Swamp Expansion (by Farcr)
    Abnormals Core (by SmellyModder)
    Ding (by ohaiiChun)
    Comforts (by TheIllusiveC4)
    Placebo (by Shadows_of_Fire)
    The One Probe (by McJty)
    Conjurer's Cookbook (by cosmicparticl)
    Better Advancements (by way2muchnoise)
    Sweet Concrete (by rahalabytes)
    Lotta Terracotta (by rahalabytes)
    Bookshelf (by DarkhaxDev)
    Styled Blocks Mod [FORGE] (by The_Wabbit0101)
    Overpowered Mending (by RakSrinaNa)
    MoreVanillaLib (by MelanX)
    Building Gadgets (by Direwolf20)
    The Endergetic Expansion (by endergized)
    Extreme sound muffler (Forge) (by LeoBeliik)
    Skinned Carts (by Mrbysco)
    Slime Tweaks (by DarkhaxDev)
    Phosphor (Forge) (by jellysquid_)
    End Teleporters (by Markus1002)
    Ensorcellation (by TeamCoFH)
    Autumnity (by Markus1002)
    Essentials (by Technomancer_isTaken)
    Incubation (by Markus1002)
    Pane In The Glass (by MongoTheElder)
    Curious Elytra (by TheIllusiveC4)
    Upsizer Mod [FORGE] (by The_Wabbit0101)
    Curios API (by TheIllusiveC4)
    Crafting Tweaks (by BlayTheNinth)
    Snow Under Trees (by bl4ckscor3)
    Macaw's Bridges (by sketch_macaw)
    Packing Tape (by gigaherz)
    Charm (by svenhjol)
    Quark (by Vazkii)
    AutoRegLib (by Vazkii)
    Engineer's Decor (by wilechaote)
    ExtraButtons (by Texelsaur)
    Torch Slabs Mod (by EndlesNights)
    Extended Lights (by polyvalord)
    Flamboyant (by equinoxrex_)
    Additional Bars (by CodenameRevy)
    Enchantment Descriptions (by DarkhaxDev)
    Easy Elytra Takeoff (by Serilum)
    VanillaFoodPantry Mod [FORGE] (by The_Wabbit0101)
    SwingThroughGrass (by exidex)
    Just Mob Heads (by Serilum)
    Atmospheric (by paradiscal)
    Slabs, Stairs, Walls (by IchHabeHunger54)
    FastWorkbench (by Shadows_of_Fire)
    Gauges and Switches (by wilechaote)
    AppleSkin (by squeek502)
    Fast Leaf Decay (by olafskiii)
    Bountiful (by ejektaflex)
    Double Slabs (by CJMinecraft01)
    Just Enough Items (JEI) (by mezz)
    Bloomful (by bageldotjpg)
    Macaw's Windows (by sketch_macaw)
    Caelus API (by TheIllusiveC4)
    Extra Boats (by Markus1002)
    Patchouli (by Vazkii)
    FastFurnace (by Shadows_of_Fire)
    Kottle (by Alex_wells)
    Save My Stronghold! (by YUNGNICKYOUNG)
    Macaw's Doors (by sketch_macaw)
    Simply Tea! (by EpicSquid319)
    Ender Mail (by Chaosyr)
    Connected Glass (by SuperMartijn642)
    Shulker Tooltip (by ZephaniahNoah)
    Decorative Blocks (by stohun)
    Conduits Prevent Drowned (by Serilum)
    Mouse Tweaks (by YaLTeR)
    Upgrade Aquatic (by minecraftabnormals)
    Storage Drawers (by Texelsaur)
    Carrots Library [FORGE] (by The_Wabbit0101)
    Vanilla Excavators [Forge] (by MelanX)
    Bambootiful (by bageldotjpg)
    JourneyMap (by techbrew)
    Pick Up Notifier (by Fuzs_)
    Goblin Traders (by MrCrayfish)
    Sound Filters (by Tmtravlr)
    I Like Wood (by yamahari_)

**Comment by Wabbit0101** [comment]
The recipe is visible in the [5.5.1 version on CurseForge](https://www.curseforge.com/minecraft/mc-mods/vanillafoodpantry-mod/files/3072396).
