### ISSUE TITLE
[Fix] Using stacked stews

### ISSUE THREAD

**Issue by F43nd1r** [Wabbit0101/mods_hoardercraft#110]
This should fix eating stacked stews. Would be nice if this could be included in this mod.
I tried to do the same for buckets, but I couldn't find an appropriate event.
```java
    @SubscribeEvent
    public void onItemUseFinish(LivingEntityUseItemEvent.Finish event) {
        ItemStack itemStack = event.getItem();
        Item item = itemStack.getItem();
        if (item instanceof SoupItem || item instanceof SuspiciousStewItem) {
            if (itemStack.getMaxStackSize() > 1) {
                LivingEntity entity = event.getEntityLiving();
                if (entity instanceof PlayerEntity) {
                    PlayerEntity player = (PlayerEntity) entity;
                    if (!player.abilities.isCreativeMode) {
                        player.addItemStackToInventory(event.getResultStack());
                        if (itemStack.getCount() > 1) {
                            itemStack.shrink(1);
                            event.setResultStack(itemStack);
                        } else {
                            event.setResultStack(ItemStack.EMPTY);
                        }
                    }
                }
            }
        }
    }
```

**Comment by llssc** [comment]
I was going to start another issue but I found this

I was going to ask if there is a way to override by checking the output of right clicking and see if it is liquid or storage for some entity, it will not discard the rest of the stack and behave "normally," but I guess that is not the case since this issue was open since May and it is still the same...

**Comment by Wabbit0101** [comment]
This might be integrated into the next **change** release of Upsizer for 1.16 as it adds functionality that isn't strictly "just upsizing the max stack size". The current 1.15/1.16 are just recompilations hence you don't see this.

**Comment by Wabbit0101** [comment]
Check [the lastest 1.16.4 release of Upsizer](https://www.curseforge.com/minecraft/mc-mods/upsizer-mod/files/3139004). You'll need to turn this on in the config (it's off by default b/c lots of mods also fix this so it is conservative by default).
