### ISSUE TITLE
Custom settings are removed from the file

### ISSUE THREAD

**Issue by ArturilloD** [Wabbit0101/mods_hoardercraft#114]
Hi, I am trying to make the items can be stored in chests and inventory in a quantity greater than a stack but when reloading the game it is deleted from the configuration file, it allows me to give it a larger size for example 128 diamonds, but at the time of Trying to put it in inventory or a chest it only saves for stacks of 64, am I doing something wrong or just can't? Thanks in advance. Regards

**Comment by Wabbit0101** [comment]
My understanding: the inventory itself (the chest or hopper for example) will cut the size down to its own max size as each tracks its own max size independent of the item max size which this mod changes. Unfortunately most inventories are hardcoded to a max of 64 including many Forge adapters _and the inventories max stacksize takes precedence_ over the item max stacksize which is looks like your config is being ignored (it's not).

Upsizer mod is really easy for getting items TO 64 stacksize. To get your stack sizes over 64 you'll need a core mod that actually alters the Java class code of these inventories. There are a couple for Minecraft 1.12, but I'm not aware of anything for newer Minecraft versions. For 1.12 try [(StackUp!)](https://www.curseforge.com/minecraft/mc-mods/stackup)

**Comment by ArturilloD** [comment]
I understand, thank you very much, it seems if it works with upsizer when
using a mod like inventory tweaks or something like that, when organizing
the inventory the established quantity is put but then it can no longer be
put manually. We will wait for someone to do it for the newer versions.
