### ISSUE TITLE
 [VFP Suggestion] VFP for mc 1.14.4 is not compatible for Pam's Harvestcraft2.

### ISSUE THREAD

**Issue by Summerpupp** [Wabbit0101/mods_hoardercraft#115]
Hi,

I'm on 1.14.4 now and I found Pam's2 and VFP is not compatible. Also, I recommend you open a Patreon so that we can donate to your excellent work. I think Pam's "Donate 10$ and I will create a new kind of food for you in the mod" is a good idea.

Thanks!

**Comment by Wabbit0101** [comment]
I'm not sure what you mean by "not compatible". If you mean some items do not work in recipes automatically, you need to look at the associated 1.14.4 datapacks on CurseForge (these are additional files --[ look at the base 1.14.4-5.0 release for the "Other files" area](https://www.curseforge.com/minecraft/mc-mods/vanillafoodpantry-mod/files/2883053)).

If these datapacks are not what you're looking for, please reopen this issue **with better details of the incompatiblity** as it may be simple additions to the existing 1.14.4 datapacks.

Regarding Patreon: I mod for my and my family's fun and it's nice that other people get some enjoyment from the mod as well. No $$ is required. If you have suggestions or enhancement requests please post them here. Most of the new items added to VFP from 1.12 forward have been suggestions from people using the mod like yourself.
