### ISSUE TITLE
NPE when Ice and Fire dragon kills Wolf

### ISSUE THREAD

**Issue by viveleroi** [Wabbit0101/mods_hoardercraft#116]
vanillafoodpantry-mc1.15.2-5.5

I assume the code is expecting it's always a player killing a wolf.

```
java.lang.NullPointerException: Ticking entity
	at org.jwaresoftware.mcmods.lib.SharedGlue.getActiveHandOrMain(SharedGlue.java:918) ~[?:mc1.15.2-2.5] {re:classloading}
```

https://pastebin.com/C6Awpsxg

**Comment by Wabbit0101** [comment]
Check if the issue has been fixed with [the 5.5.1 version on CurseForge](https://www.curseforge.com/minecraft/mc-mods/vanillafoodpantry-mod/files/3072396).
