### ISSUE TITLE
Using stacked stews essentially gives you an infinite amount of stews [Upsizer]

### ISSUE THREAD

**Issue by Danny404Error** [Wabbit0101/mods_hoardercraft#120]
Hi there! Thanks for making this amazing mod, I've been looking for one that makes stews viable during survival/hardcore. However, I ran into an issue.
It seems that if you eat any stacked stews (only tested this with mushroom stew in my hardcore game, other stews/soups might be affected too) above 2, it will consume one of the stews and, on top of that, gives you a LOT more stews than you had originally. All my settings should be default; I've just started playing with this mod.
I'd appreciate it if you could look into this issue and see if it's something you can fix :)

**Comment by Wabbit0101** [comment]
Please indicate which version and can you attach your config. I need your config to verify the issue as I cannot reproduce with default settings (16x stews) in latest 1.16.4 release 3.1.

**Comment by Danny404Error** [comment]
I'm using 1.16.4 release 6.1 (latest version). My version of forge is outdated a little bit, I'm still on forge 35.1.0. Here's my config!
[wabbity_upsizer.zip](https://github.com/Wabbit0101/mods_hoardercraft/files/5702783/wabbity_upsizer.zip)
I'll try seeing if the issue persists
EDIT: Hmm, I can't replicate this issue anymore, at least in the overworld. As far as I know the issue occurred in the nether. Going to test it there now.
EDIT 2: Okay, weird. I can't seem to be able to reproduce it anymore, maybe it was a one time bug that fixed itself or something

**Comment by Wabbit0101** [comment]
After looking at the patch to fix stackable stews, it is possible for this duping to occur if you have two mods trying to do this...Upsizer gives you back the incoming result (which "should" be a bowl but might not be if there is another mod) and decrements the existing stack...in the next release, I will guard against the possibility for vanilla stews (the only thing Upsizer patches).

**Comment by Danny404Error** [comment]
Huh, now that I think about it, it's possible the duplicating occurs from the BetterPvP mod, since I use it to quick eat my foods. I'll test this out right now
edit: okay no it wasn't, just tested that out. But I'm looking forward for the next release!

**Comment by Wabbit0101** [comment]
I am unable to recreate this issue. I have posted update with the hardened code to CurseForge at: [https://www.curseforge.com/minecraft/mc-mods/upsizer-mod/files/3172126](https://www.curseforge.com/minecraft/mc-mods/upsizer-mod/files/3172126). Reopen if issue reoccurs.
