### ISSUE TITLE
lib_carrots requirements crashing on startup with the latest lib_carrots from CurseForge

### ISSUE THREAD

**Issue by soulhakr** [Wabbit0101/mods_hoardercraft#124]
[crash-2021-01-24_12.24.05-fml.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/5862919/crash-2021-01-24_12.24.05-fml.txt)

**Comment by Wabbit0101** [comment]
This is not an error. The error report is telling you the issue:

**Failure message: Mod vanillafoodpantry requires carrots 3.0b1**
**Currently, carrots is 3.0b3**

You're using the wrong version of the library for the version of VFP that you have installed.
