### ISSUE TITLE
[1.12.2 VFP] Some TAN compats aren't working, also a broken recipe or two

### ISSUE THREAD

**Issue by Darkmega18** [Wabbit0101/mods_hoardercraft#125]
I'm in 1.12.2 using the latest vanilla food pantry while running forge 2855.

Issue is I've tried chilled juice and warming soups and I don't get the chilled food or warming food effects.

But warming up potted water works and gives the advertised effects, however chilling potted water just gives me base potted water so I can't test if it works.
![image](https://user-images.githubusercontent.com/8104689/107875888-8bc77380-6f16-11eb-8067-0bfed9613b38.png)

I also have a lack of applecore style hydration readouts. Not sure if maybe it's just cuisine's own icons playing up with it perhaps however. since it adds a floating food type icon with saturation to show what can and can't be used in it's dishes.
![image](https://user-images.githubusercontent.com/8104689/107875920-d21cd280-6f16-11eb-92ac-9e4957c5252f.png)

As a side thing the cactus pads and steamed cactus heart recipes are busted, like so:
![image](https://user-images.githubusercontent.com/8104689/107875876-70f4ff00-6f16-11eb-9adc-bea35b8d63a8.png)
(witness, my invisible cactus!)

Could these issues be related to using the 1.12.2 beta version (version 141) of tough of nails? I'm using it as it's required by cuisine unfortunately otherwise the game blows up since I guess they have compatibility stuffs also. :V

**Comment by Wabbit0101** [comment]
Could you provide details for the versions of: Cuisine, and JEI. 

As you note, these seems to be something another mod  (maybe Cuisine) is doing as all of the noted issues are things mods can interject and cause: overriding the on-consumed method (hence blocking the warming/cooling from VFP), messing with the tooltips (hence stomping on the VFP and Applecore tooltips), and messing with JEI's previews.  I can try to confirm this is the case but if it is, there's not much VFP can do about it.

**Comment by Darkmega18** [comment]
Latest crafttweaker and pams is present as a side.

JEI is 1.12.2-4.16.1.301
and cuisine is 0.5.22-build929

I've come across the cactus pad and steamed cactus heart issue in my previous pack, timeless technician but never had TAN, so I never knew of when the tan stuff started breaking. 

I can send a version of the modpack I'm working on currently as it stands for you to take a look at if that could help?

checking through what does and doesn't actually work:

the cactus heart fails to work:
![image](https://user-images.githubusercontent.com/8104689/107884912-6ef96300-6f4b-11eb-8c1a-fe0d0dc5e911.png)

but the cactus pads do work regardless:
![image](https://user-images.githubusercontent.com/8104689/107884921-7caee880-6f4b-11eb-82cc-dc43c4edc989.png)

potable water doesn't chill (reading it back though, is it meant to be able to be chilled?)
![image](https://user-images.githubusercontent.com/8104689/107884963-bbdd3980-6f4b-11eb-8ef9-7a221bd73ecc.png)

but it does heat
![image](https://user-images.githubusercontent.com/8104689/107884973-c697ce80-6f4b-11eb-9776-f0f8d24f97b1.png)

juice chills properly but leaves a bottle but doesn't provide cooling effects as wanted
![image](https://user-images.githubusercontent.com/8104689/107885027-0068d500-6f4c-11eb-99bb-ae629c706994.png)

effects are advertised as being milk refreshable, but they don't. I just drank the hot water then milked and only lost the resistance effect.

**Comment by Wabbit0101** [comment]
A link to the modpack would be good. I can verify/test things from my end.

**Comment by Darkmega18** [comment]
Roger that. lemme just make sure alls in order and it runs (since I was crafttweaker editing some stuff last night etc and having to double check it all works) and then zip it up and send soon.

**Comment by Darkmega18** [comment]
apologies, my day got sidetracked into helping the dev of another mod playtest and develop and clearing up some warframe things and stuff. I've finally send sent the pack. it's in a dropbox link since as it stands curseforge is still improperly setting some mods as overrides instead of into the download manifest, so it's around 60 mb as a zip, but just load it into curseforge and run and it should all be there. (199 jars and 2 folders in the mods folder)
https://www.dropbox.com/s/93qwfl7pebd7175/Super%20Hostile%20Expanded-0.3a.zip?dl=1

also, don't mind the title screen. I'm not vechs, and it's not exactly the super hostile modpack anymore. since it was initially just an edited and stacked fork of that pack to play with my friends with my usual added fineries and minecrafting requirements... but it's been evolving into something similar but... well, thicker. :V

**Comment by Wabbit0101** [comment]
I was able to do a bit of testing with the pack you provided.

> Issue is I've tried chilled juice and warming soups and I don't get the chilled food or warming food effects

These secondary food effects **don't occur unless the player is in distress** (ie being hurt). For example if player is suffering from hypothermia, most warmed food will trigger the warming effect. Sometimes the effect can be stacked (not sure of details... it's been a long time since 1.12...I believe potable water is the most effective way to cooldown, juices are best thirst replenishers, and heated stews and/or soups are best way to warm up.) I confirmed the effects in the pack. 

>  But warming up potted water works and gives the advertised effects, however chilling potted water just gives me base potted water so I can't test if it works.

You cannot chill potable water in 1.12. The recipe is there to actually cool down heated potable water quickly. In 1.12 JEI it was tricky to get recipes to show items differently if only NBT is different for custom recipes.

> I also have a lack of applecore style hydration readouts.

This is not VFP. VFP doesn't add those tooltips so seems two other mods are in conflict.  VFP does implements the IDrink interface/cap information.

> As a side thing the cactus pads and steamed cactus heart recipes are busted, like so:

This is a known 1.12 VFP compatibility issue with block substitution. Apothesis is replacing Minecraft's Cactus Block and VFP's recipe is using the disabled reference. You might be able to work around this by adding a CraftTweaker recipe (that just is a copy of VFP's recipe)...the CT recipe will get the proper substituted block.

> juice chills properly but leaves a bottle but doesn't provide cooling effects as wanted

The bottle duping is an issue caused by something Cuisine is doing. Don't know what tho' and that mod is discontinued w/ no support so...The chilling does work but only if the player is distressed (see answer above)

> effects are advertised as being milk refreshable, but they don't. I just drank the hot water then milked and only lost the resistance effect.

Not sure what "advertised as being milk refreshable means" but the warming/chilling food effects are "stubborn" effects that do NOT accept milk as a curative. They remain active even if player needs to drink milk to remove debuffs like nausea, poison, mining fatigue, etc.

**Comment by Darkmega18** [comment]
![image](https://user-images.githubusercontent.com/8104689/108211892-5e323280-7181-11eb-878b-4e1f9dbb1f7f.png)
that. indicates they're basic, rather than stubborn in the wiki.

Oh, didn't know there was a hard requirement of the cooling and warming effects to trigger. that explains it then. good to know, and will definitely make that a point when I touch on warming and cooling foods in quests.

Oh, shoot, I had no idea cuisine was discontinued. I've been using it for sometime just offhand without checking it's page because I love it's mechanics. D:

Well alrighty, I'll fix the cactus thing then in post.

That seems to be all the main things then, covered as just me being dumb or potentially just missed instruction. since now that I know, I see the point made in the first line of the temperature set in the wiki. but to me initially that was just you saying that they're damaging effects which can be staved off with the food, and not necessarily that you need to be suffering from them in the first place to get the effects at all. :V could possibly use slightly stronger language, or a key point bullet required down below to emphasize the need to be suffering before any effects are felt.

otherwise, yep, all seems to be in order then. cause cactus is easily fixed with crafttweaker.

**Comment by Wabbit0101** [comment]
You...read...the...wikidocs..?! Thank you! (unfortunately this bit of doc is out-of-date...I have fixed it; sorry about that). As you say the docs should probably also emphasize that "very hot" or "very cold" means hypothermia and hyperthermia have set in. And I too liked Cuisine and am sorry to see it abandoned.

Let me know if there are any other issues with VFP in your pack.

**Comment by Darkmega18** [comment]
I sense a touch of happy frustration there. not enough people read em and then ask stupid questions? I actually had to check over it a couple times in that little spot to make sure I wasn't just reading poorly or missed something.

y'know. you could always take over Cuisine? ;) MIT could let you do that, right? not that it's super disfunctional or anything. probably just needs some tweaks here and there and it'd be fine.

and alrighty, thanks, I will.
