### ISSUE TITLE
[Styled Blocks] Failed to load world/Failed to load datapacks

### ISSUE THREAD

**Issue by Blatts12** [Wabbit0101/mods_hoardercraft#127]
Failed to load datapacks, can't proceed with server load java.lang.IllegalStateException: Failed to load world

I added Styled Blocks to Enigmatica 6 and i can't load my world.

[error](https://gist.github.com/Blatts12/c3fb42625377c1fdd02bf1f084b93b7f)
[debug.log](https://ln2.sync.com/dl/c94656d70/ck9k84xm-ad8qmc5y-zvtztenh-25uwq9ew/view/text/4335214800009)

**Comment by Wabbit0101** [comment]
I can put in code to workaround this but the core issue is here:
`cofh.thermal.core.event.TCoreCommonSetupEvents.idRemap(TCoreCommonSetupEvents.java:86)`

This is calling items to get their burnTimes before tags have been loaded. JEI just fixed similar issue.

**Comment by Wabbit0101** [comment]
Try the lastest [beta4](https://www.curseforge.com/minecraft/mc-mods/styled-blocks-mod/files/3232072) and reopen if you're still having issues.  Don't forget to use the latest CarrotsLib as well (that's where the workaround exists.)
