### ISSUE TITLE
1.12.2 VFP adds HarvestCraft compatibility script when HarvestCraft isn't installed

### ISSUE THREAD

**Issue by cryoteeth** [Wabbit0101/mods_hoardercraft#129]
When VFP's Pam's HarvestCraft compatibility is set to the default autodetect option, the mod still adds the CraftTweaker script (04_pams_hc_ie_fermenter.zs), even though I don't have HarvestCraft installed! 

Forcing the compatibility off stops the script being re-added.

This doesn't affect gameplay, but does result in a huge cascade of errors from CraftTweaker!

**Comment by Wabbit0101** [comment]
Not sure what this is related to. VFP does not include CraftTweaker scripts. If this is part of a modpack, looks like you need to talk to the modpack author about their script.

**Comment by Wabbit0101** [comment]
Closing as this isn't VFP's script.
