### ISSUE TITLE
No Recipe for Andesite Super Blocks

### ISSUE THREAD

**Issue by jokish63** [Wabbit0101/mods_hoardercraft#13]
I have noticed that there is no recipe to make Superblocks out of Andesite in the 1.8.9 Version
just for your Information

**Comment by Wabbit0101** [comment]
I could never collect enough of this stuff to ever miss the superblock! It's been on the to-do list for some time along with prismarine blocks. I will add Andersite blocks for the 1.8.9-r03 release.

**Comment by Wabbit0101** [comment]
Fixed since mc1.8.9-2.0 release.
