### ISSUE TITLE
I try to change the configuration for the craftable "Ozzy Liners", but it doesn't work fsr

### ISSUE THREAD

**Issue by SacredDorito** [Wabbit0101/mods_hoardercraft#130]
If I change the configuration for ozzy liners from the "Armor Underwear" mod it doesn't work

**Comment by Wabbit0101** [comment]
You need to provide more specifics w/ your comment: like **HOW** did you change the config? I cannot just guess at what you did. _And attach your changes and environment information like which version of the mod you're using_. Please re-open when you have provided information I can act on.

**Comment by SacredDorito** [comment]
nvm I figured it out
