### ISSUE TITLE
Stacked stews + Dank Storage = Infinite stew

### ISSUE THREAD

**Issue by chimericdream** [Wabbit0101/mods_hoardercraft#131]
We have both Upsizer and Dank Storage in our modpack, and I was using stews as an early-game food source (our spawn area is a mooshroom island). However, I noticed that whenever I would eat a bowl of stew, I would actually gain several more in the Dank. I asked about this on their GitHub, but was directed here, since it's more likely an issue related to the patching of stack size for the stew items.

**Comment by Wabbit0101** [comment]
Not sure how Upsizer would cause an INCREASE in the dank inventory count as upsizer's patch will cause the stew's stack to shrink not grow. As this is a dup/mod-incompatibility I'd say make sure to disable the patch altogether by setting `fix_bowl_food` to false for your modpack.

**Comment by Wabbit0101** [comment]
As far as I can tell this is a problem with their stuff. I can get infinite cookies without Upsizer even being installed: New level 1 dank. Lock cookies. Clear all cookies from my inventory and take out the last cookie from the dank storage. Begin eating that cookie...the eat action goes on forever and when I stop there's a new cookie in the dank storage and the one in my inventory may or may not be there.
