### ISSUE TITLE
1.16.5 Did not see the option to set the number of stacks

### ISSUE THREAD

**Issue by dd880602** [Wabbit0101/mods_hoardercraft#132]
How to set the number of stacks in version 1.16.5?
I want to set the stack to 64
"minecraft:saddle" has only 16 stacks by default

**Comment by Wabbit0101** [comment]
- Open your config file: **`config/wabbity_upsizer.toml`**
- Look for option named `saddles_storage_stack`
- Change value from `16` to `64`
- Restart your game or server
