### ISSUE TITLE
[1.16.5 VFP] Server crashed when eating Undead Wotsit

### ISSUE THREAD

**Issue by StarchierOrb** [Wabbit0101/mods_hoardercraft#139]
MC version: 1.16.5
Forge version: forge-1.16.5-36.2.0
VFP version: latest on curseforge (6.0)

Only crashed in multiplayer, not singleplayer.

Steps to Reproduce:
1. Eat Undead Wotsit when health is not full.

Crash report:
https://pastebin.com/hC4ushwU

**Comment by Wabbit0101** [comment]
Should be fixed in the [6.0.1](https://www.curseforge.com/minecraft/mc-mods/vanillafoodpantry-mod/files/3441203) version.
