### ISSUE TITLE
Slab Crash - Styled Blocks Mod [FORGE]

### ISSUE THREAD

**Issue by Cerberus06** [Wabbit0101/mods_hoardercraft#140]
Hi

The reason for this is because putting a slab of the mod and chopping it causes the game to close, I play in version 1.16.5

Attached the crash file.

Greetings.
[crash-2021-09-17_08.49.48-server.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/7186262/crash-2021-09-17_08.49.48-server.txt)

**Comment by Wabbit0101** [comment]
You're using a newer version of the Carrots Library that is causing an issue (StyledBlocks 6.0b5 is built against the carrotslib-mc1.16.5-3.0b5 version). Please download the [older library version](https://www.curseforge.com/minecraft/mc-mods/carrots-lib/files/3268243) and try in your environment. That should help with the crashes; I will rebuild the mod against the 3.0.1 (latest) library as soon as I have a bit of time.

**Comment by Cerberus06** [comment]
HI

Perfect, I just changed the version and problem solved.

Thank you very much for the help.
