### ISSUE TITLE
[VFP:1.16.5 Bug] Nutrition cannot be blacklisted and reassigned.

### ISSUE THREAD

**Issue by Darkmega18** [Wabbit0101/mods_hoardercraft#144]
**VFP:** version-6.0.1
**Forge:** 36.2.33
**Carrots lib:** 3.0.1
**Diet:** 1.0.3.1
Modpack?: yep, big one...

I'm having some issues with creating some custom food groups using vanilla food pantry along with diet. Apparently regardless if I remove, empty and overide all the base diet tags and substitute my own, blacklist all your items and then only allocate the ones that I want changed with my own tags some of your items are just deciding to mystically get their own values back.

Is there anything I can do about this...?

**Comment by Wabbit0101** [comment]
Can you give me an example? There are some "dynamic" foods like deckers that assign values programatically via IMC apis. These can't really be overridden with a datapack in the current 6.x versions.  Most of the rest *I think* are governed by the declarations in VFP's jar's 'data.diet.tags.items' files...Give a few examples and I'll be able to better diagnose.

**Comment by Darkmega18** [comment]
oh sorry, forgot to check this off. I just had some cross mod issues with the sheer amount of tags you have available. because of Diet mod it was picking up food values from items from some other mods I had which had tags it could draw from which resulted in some confusion and frustration when food groups not intended were showing up for completely arbitrary things like bottles of water and stuff.
But I eventually figured out there was a tag I could use to make items not share their values anymore and that fixed it soon after. Diet also made a feature that can stop that overall also, so there shouldn't be an issue anymore.

**Comment by Wabbit0101** [comment]
Ok. Reopen if there are any issues then.
