### ISSUE TITLE
Simple Difficulty Compatibility

### ISSUE THREAD

**Issue by reddvilzz** [Wabbit0101/mods_hoardercraft#145]
Using Simple Difficulty which is like a fork for Tough As Nails for 1.12.2 the configuration for Armor Underwear it's not showing up.

**Comment by Wabbit0101** [comment]
For 1.12, the Armor Underwear support code is available in the Carrots library only if a mod with id = "toughasnails" is present. The code is literally removed by Forge unless TAN is present as the code depended on classes (like API interfaces and such) from TAN (see the @optional annotation in Forge 1.12...it was awesome!).  That is why there is nothing for Armor Underwear.

Simple Difficulty is its own distinct mod with a different id. I would need to create a new 1.12 library port for SimpleDifficulty using its version of TAN's classes. As 1.12 is now in archive-mode for my mods, that isn't going to be done unfortunately. When Simple Difficulty upgrades to 1.18+, I'll be happy to provide a Carrots library plugin for it; that's the best I can offer at this time.

**Comment by reddvilzz** [comment]
Okay then, thank you for responding. I'll try mention this to Simple Difficulty dev.
