### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by ArtixAllMighty** [Wabbit0101/mods_hoardercraft#15]
Could you release a list of the oredict name you use to register some of your foods ? i'd love to get more compatibility out of my mdo with yours

**Comment by ArtixAllMighty** [comment]
also, a 'food' tag, for everything you can cook, but isn't food in the first place (like the pumpkin block that you can cook into slices !) I've added exactly that tag in my own mod to check as a secondary resort for food items that might not be food. 

I'd give you a PR, but you don't have code released :/

**Comment by ArtixAllMighty** [comment]
just noticed that you have registered eggs ingredients under "ingredientEgg". i wanted to point out that "egg" is already a valid forge addition to the oredictionairy ! no need to register egg to ingredientEgg as well imo

**Comment by Wabbit0101** [comment]
They are two very distinct things. 'egg' refers to raw eggs (usually animal drops); I use this id when appropriate -- ie when i ONLY want raw eggs. 'ingredientEgg' refers to 'egg' -or- egg substitutes such as powdered eggs and egg substitutes appropriate for low-cholesterol diets (yes, some of my family qualifies). So the two are intended for quite different purposes. Also an 'egg' can refer to very large eggs (some 1.8.9 mods even had HUUGGE dinosaur eggs!); 'ingredientEgg' implies 1 portion of egg (so a dinosaur egg might produce 8 powdered eggs allowing the player to get better rationing). Hope that clarifies.

**Comment by Wabbit0101** [comment]
Artix...Please open one issue per suggestion. It makes it easier to manage and keep the conversation clear for others.

**Comment by Wabbit0101** [comment]
Regarding the 'food' tag: there are a lot of existing APIs out there that already do something like this. AppleCore comes to mind and the new ToughAsNails or CookingForBlockheads mods. I would say check out those APIs if you're looking for something for your own stuff. VFP itself uses ItemFood for all of its edible items. Also VFP doesn't make existing items like a pumpkin block technically edible -- just like you can't eat a melon block but you can break it (or in VFP case 'cut and cook it') into edible components.
