### ISSUE TITLE
[Bug] Can't apply liners to modded armor + goopaks not working

### ISSUE THREAD

**Issue by Catomax262** [Wabbit0101/mods_hoardercraft#150]
For some reason i can't apply any liner to modded armors.
Goopaks in this case aren't protecting from heat/cold.

**Comment by Wabbit0101** [comment]
You need to supply more information that what is shown. For example what version of Forge and the mod is this? What are these"modded armors"? What liners are you trying? What survival mod is present (TAN, Survive, etc.)? Does it work for vanilla armors? What are your configs (armors most be INCLUDED to work) -- include these. Please update with proper details and reopen your report.
