### ISSUE TITLE
natron crystals/ore

### ISSUE THREAD

**Issue by xXAu5t3nXx** [Wabbit0101/mods_hoardercraft#152]
I cannot find natron anywhere in the world. I have tried googling where I should be looking and I just get the "overworld" as the location. Is anyone else having trouble finding this? if not, can someone point me in the right direction?

**Comment by Wabbit0101** [comment]
I need to know: what version of the mod are you using and (important) is it part of a modpack or are you using it standalone?

**Comment by xXAu5t3nXx** [comment]
We are using .95a

**Comment by xXAu5t3nXx** [comment]
Sorry. It is rogue like dungeons 2 .95a

**Comment by Wabbit0101** [comment]
For that modpack, I believe natron ore generation is disabled. You will need to look for a villager that sells it (I read this tip on a reddit thread, but you might want to ask in the modpack's discord for details.) HTH
