### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Ceimnithe** [Wabbit0101/mods_hoardercraft#153]
Sorry for being vague, I don't have the time right now to really figure out why this is happening. I've got a lot of mods loaded so I'm sure it's an incompatibility issue; I'll throw a crash report up here and do some process of elimination later if I have time.

MC 1.18.2
Forge 40.2.0
CarrotsLib 4.0

[crash-2023-03-16_03.27.37-client.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/10987836/crash-2023-03-16_03.27.37-client.txt)

**Comment by Wabbit0101** [comment]
Maybe this is not the right crash log? Note that CarrotsLib is a Forge-only mod. According to this log your crash is happening inside a Minecraft sound-related class, not CarrotsLib. Also I don't even see carrotslib in any stacktrace (implying it's not even involved indirectly). However, there are lots of mixin-related classes on the immediate stack...

This:
`java.lang.NoClassDefFoundError: Could not initialize class org.orecruncher.sndctrl.audio.SoundUtils`

and this:
`Recovery reason: java.util.concurrent.CompletionException: java.lang.IllegalAccessError: class org.orecruncher.sndctrl.audio.SoundUtils tried to access private field net.minecraft.client.sounds.SoundManager.f_120349_ (org.orecruncher.sndctrl.audio.SoundUtils is in module dsurround@5.0.0.4 of loader 'TRANSFORMER' @d7bbf12; net.minecraft.client.sounds.SoundManager is in module minecraft@1.18.2 of loader 'TRANSFORMER' @d7bbf12)`

coming from a Minecraft class is indicative of an incompatibility of your core mods (like Minecraft, Forge/Fabric, Rubidium, etc.)

Please re-open when you've had some time to check above notes and are sure it's CarrotsLib (remove the mod and see if this goes away for instance).

**Comment by Ceimnithe** [comment]
In my infinite wisdom I do not believe that I mentioned this is specifically a CL 4.0 issue. Backrolling to 4.0a3 fixes the problem. Still, it is definitely carrotslib, the crash stops when I remove it and comes back immediately when I reactivate it (I'm using the curseforge launcher). It crashed before I even got to the forge loading screen. Just incase I added the wrong log, I'll add the one that is 100% certainly from this crash lol. Wouldn't put it past me to make that mistake. I also saw the TAN plugin and added that hoping maybe it was an issue I overlooked, still crashing. 

Updated to Forge 40.2.1.

[crash-2023-03-25_04.15.36-client.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/11068377/crash-2023-03-25_04.15.36-client.txt)

Thank you for taking the time to look into this by the way.

**Comment by Wabbit0101** [comment]
I think this is an issue with the dynamic surroundings mod...there are many reports that are basically the same as the one you're reporting...and dynamic surroundings is the exact mod that is on the stack triggering the error. CarrotsLib 4.0 just seems to cause a tiny change in how the starting transformations are being done (eg concurrency ordering) and the issue surfaces. Here is a report that is almost identical stacktrace: https://github.com/Nyfaria/DynamicSurroundingsResurrected/issues/19. And it seems to be a long-standing issue based on reports like this one for last year: https://www.minecraftforum.net/forums/support/java-edition-support/3153849-can-anyone-help-me-to-figure-ot-what-mod-is. 

Try removing dynamic surroundings (its the coremod..see **dsurround@5.0.0.4**) temporarily and putting in CarrotsLib 4.0, see if the issue goes away.

**Comment by Ceimnithe** [comment]
Yep, right on the money. Updated to 4.0, removed DS and it loaded just fine. That's a shame, should I report this to the DS github instead then?

**Comment by Wabbit0101** [comment]
It's already referenced automatically (by github itself) from the link I inserted above. I also see at least two more issues related to this error...I think the author might have moved on to mc1.19+ as nothing has been done for any of those issues. I would just add a watch on that issue to get notified if author marks fixed|closed eventually.
