### ISSUE TITLE
Crash with Redstone Aresenal

### ISSUE THREAD

**Issue by Sember225** [Wabbit0101/mods_hoardercraft#154]
Minecraft Ver: 1.18.2
Forge Ver: 40.2.0
Armor Under Ver: 3.0
CarrotsLib Ver: 4.0
Redstone Arsenal Ver: 6.2.0.13
Pastebin: https://pastebin.com/VATqFKYP

Crashes on startup. 

Removing Armor Under and CarrotLib fixes this crash. 
Any help would be appreciated.

**Comment by Wabbit0101** [comment]
This looks like an incompatibility between mixins. I'll have to look into that pasted stack trace to see exactly how the loop is forming. If you still want to try armorunder you can disable ArmorUnder's mixin by turning OFF **enable_mixins** in the 'wabbity_armorunder.toml' config file.

**Comment by Wabbit0101** [comment]
Should be fixed by [version 3.0.1 on CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/armor-underwear-mod/files/4502893)
