### ISSUE TITLE
[Suggestion, VFP] Add a netherwart-less recipe for awkward potions

### ISSUE THREAD

**Issue by Catomax262** [Wabbit0101/mods_hoardercraft#155]
With Survive, nether temperature management is pure hell. To counter i want to get some fire resistance potions, but the nether heat is so strong i die every time, also, you can't place water or ice, or else, and nether warts are kinda rare, and only are obtained inside the horrible nether heat.

**Comment by Wabbit0101** [comment]
If you are using VFP, try checking ruined portals' chests.. VFP adds netherwarts there (I'm assuming mc-1.18.2). You can also try eating APPLE snocones in the nether; these have an extra cooldown buff to them!
