### ISSUE TITLE
Not working in nether.

### ISSUE THREAD

**Issue by Pantheris2019** [Wabbit0101/mods_hoardercraft#157]
Minecraft Version: 1.18.2
Forge Version: 40.2.2
Mod version: 3.0.1

Steps to reproduce:
Craft armors that have the maximum number of liners allowed for each piece.
Go into the nether
Burn to death because the cooling liners just DO NOT WORK.

As far as I gathered, maxing out the cooling liners in the armors should allow one to venture into the nether with no issue.

**Comment by Wabbit0101** [comment]
You have to list what survival mods you have included...I have no idea what you're describing--- Just armor underwear? Tough as Nails? Survive? Do you have the right plugin for the survival mod installed? What kind of armor are you wearing and did you include that armor in the configs to make liners work? Are you using Cold Sweat?...like I said... I have no clue what you're describing. Please update the report and reopen.

**Comment by JrBuzzWorthy** [comment]
Going to reopen this issue

Forge Version - 40.2.10
Carrots Library : Version 1.18.2-4.0
Armor Underwear : Version 1.18.2-3.0.1
Tough as Nails : Version 1.18.2-7.0.0.73

Installed and Tested on Fresh Client

Any of the Thermal Liners [Cool Liner, Warm Liner] & Special Liners [Ozzy, Ollie, Otto] do not work
Wool and Leaf sets work as intended but upon adding any of aforementioned liners they do not work on any other armour set

The Ollie & Otto set also have some peculiar issues
The Ollie set when equipped will still cause you to start burning in the nether for example but you will not lose any health only a constant damage effect
The Otto set when equipped will simply remove the ability to freeze in it's entirety
For both of these sets you only require a single piece for these effects to be active

The GooPaks have a similar issue as they won't warm or cool you down
Whereas a bucket of Lava will warm you
