### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Chris6ix** [Wabbit0101/mods_hoardercraft#162]
Hey, I tried to add your SmartHoppers mod to my RLCraft pack, but it causes the game to crash on startup.
Here is the crash log:
[crash-2023-10-08_16.03.26-client.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/12840910/crash-2023-10-08_16.03.26-client.txt)
Any idea how to fix this?

**Comment by Wabbit0101** [comment]
Item substition in 1.12 was a pain...Looks like another mod has replaced the vanilla slimeball or slime block so when smart hoppers tried to create a recipe, it gets an empty stack reference for the vanilla item. If it does not affect the workings of your modpack, I would disable the quark mod's slime block module.
See issue: #69

**Comment by Chris6ix** [comment]
Hey, thanks for the quick response.
Yeah, disabling `Slime blocks bounce off sides` in `quark.cfg` fixes the crash.

However, I think I'm not going to use your mod after all, because it is just unnecessarily overcomplicated and adds so many things that have nothing to do with hoppers. I think I'm just going to use the simpler Vanilla method.

Thanks for your help anyway.
