### ISSUE TITLE
[VFP, 1.11.2] Crash eating Broth with Bread as a single item with AppleCore

### ISSUE THREAD

**Issue by gchpaco** [Wabbit0101/mods_hoardercraft#18]
I've been experiencing a crash in Vanilla Food Pantry when eating single Broth with Bread (and other items that return a bowl) when there's only one item in the stack, when using AppleCore 2.2.0.  I managed to get a minimal test case:
1. install AppleCore 2.2.0
2. get some hunger
3. eat single Broth with Bread
4. game crashes.

Interestingly, if there is more than one Broth with Bread in the itemstack, it works fine.  So I suspect this is something odd with how Vanilla Food Pantry handles replacing the itemstack with a bowl.  Note that vanilla food that has that same property (for example, beetroot soup) does not crash, so this is not inherently a problem with AppleCore.

[crash-2017-07-08_11.44.12-server.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/1133126/crash-2017-07-08_11.44.12-server.txt)

**Comment by Wabbit0101** [comment]
Looks like the EntityPlayer.getFoodStats() is returning the AppleCore version of FoodStats and that item does not work with empty stacks (these are non-null as of 1.11 but their underlying items can be NULL). Looks like AppleCore has a little boo-boo there (it's not checking for ItemStack.isEmpty()). The reason it triggers from VFP is I changed the ordering of when the food stats object is used (it should make no difference if empty stacks are handled OK). I'll fix to update the stats before stack is decremented and things should work (I'll check of course).

**Comment by Wabbit0101** [comment]
Bug applies to mulitple bottled items as well.

**Comment by Wabbit0101** [comment]
Fixed with https://minecraft.curseforge.com/projects/vanillafoodpantry-mod/files/2448657
