### ISSUE TITLE
1.12 versions?

### ISSUE THREAD

**Issue by gchpaco** [Wabbit0101/mods_hoardercraft#20]
Github issues is probably not the best medium for this but I dunno what the right one would be.  I've immensely enjoyed using VFP for 1.11.2, but I'm trying to compile a 1.12 pack since this is the version a lot of others have gone to, and I'm really missing a coherent extra food mod (as opposed to, say, Pam's, which is neat but not really coherent).

**Comment by Wabbit0101** [comment]
The wholesale changes to the recipe system are a pain for VFP (it does a lot programmatically to maximize commonality). I have been trying to get in the big ideas I had planned before moving on (and it will be moving on as it'll be impossible for me to keep 1.11.2 and 1.12 feature-synced). I have one bugfix release planned for "any day now" and will be switching to 1.12 recipe refactoring.

**Comment by Wabbit0101** [comment]
The first 1.12.1 beta has been posted. I won't be doing 1.12 solo but jumping to latest MC. Advancements and Recipe Book integration will come in next beta. Please report any issues w/ integration. Uses forge-1.12.1-14.22.0.2467.

**Comment by gchpaco** [comment]
Woo, TYVM!  Will test.
