### ISSUE TITLE
Upsizer cap size

### ISSUE THREAD

**Issue by MCYayes** [Wabbit0101/mods_hoardercraft#23]
So I tried to customize the config to allow significantly large stack sizes, but it seems there's some hard cap at a stack size being 64 items. Is that on purpose, or did I do something wrong?

The reason for this attempt is because I'm trying to sidestep using the Applied Energistics 2 mod for it's storage and access ability with a lighter weight mod (Upsizer), since horde storage + nomadic play style are some of the main points I'm trying to set up for a LAN party game.

Anyhow... I'm just wondering if I'm doing something wrong in my attempt to make the stack sizes large, or if it's an intentional limit.

My experimentation found that my chosen max stack size (60k items) doesn't work in any inventory (personal, chest, etc), but if I stack-select in creative, I pick up the max stack size I specified (I just can't place more than 64 in a stack into any inventory space). So I don't know if I'm doing something wrong or what.

Thanks for this mod, I still use it as it's still helpful.
Cheers!

**Comment by Wabbit0101** [comment]
Alas you're running into the max size for the _inventory_ slot in which the stack itself (whose max size upsizer updates) sits. _The inventory's max size will always win_. I also have this problem and yea it's annoying. Most vanilla inventories (player, crafting, hoppers, etc. are hardcoded to 64). Modded inventories may be more flexible. I don't know of any core mod that changes the basic inventory max size (it would have to be a core mod to update the vanilla inventories).  

Also 16K is huge. The standard inventory GUI will not render that large 16000 number properly (storage mods usually provide their own render w/ smaller fonts to overcome). Let me know if you find such a core mod!

**Comment by MCYayes** [comment]
I had a feeling it was a hardcoded cap.

Applied Energistics 2 stacks items in it's system up to 65k or something - which is accessible wirelessly with a device in the inventory.

That said tho, it doesn't do anything to change the standard stacking sizes in the inventory or for the game itself... It's a storage with access option.

No worries tho, and thanks for your work on this mod, it's quite useful! :)
