### ISSUE TITLE
Cannot eat pumpkin bread (and presumably, similar items)

### ISSUE THREAD

**Issue by Sunconure11** [Wabbit0101/mods_hoardercraft#24]
I cannot seem to eat pumpkin bread, even when my hunger is not full.

**Comment by Wabbit0101** [comment]
Is this for a single item? If you've got multiple items stacked, then no you cannot eat one partially and have others uneaten in the same slot (if this where allowed you entire stack would get decremented instead of just one).

**Comment by Sunconure11** [comment]
... It was multiple items in the same slot. Derp.
