### ISSUE TITLE
[UpSizer] Mushroom Stew bug 1.12.2

### ISSUE THREAD

**Issue by PokeMaserJ** [Wabbit0101/mods_hoardercraft#25]
So I changed Mushroom Stew to be able to hold up to 64 items, and when I ate one of the stacked stew, it ate all the stew in the stack at once and left me with one bowl
MC Version:1.12.2
Forge Version: 14.23.1.2556
UpSizer Version: 4.0

**Comment by Wabbit0101** [comment]
I can't change this. As the documentation says, some standard Minecraft items ASSUME a single stack of 1 item and do stupid things (like replacing the slot with an empty bowl blindly). Same thing for buckets, potions, etc. In these cases upsizer can help with storage, but you need to unstack the item to use it (see documentation again). This limitation applies to ALL standard items that take damage, or include some additional mechanic besides consuming (like the return of a bowl or bottle).
