### ISSUE TITLE
Some crazy worldgen issues with salt ore [1.12.2]

### ISSUE THREAD

**Issue by loudwhitenoise** [Wabbit0101/mods_hoardercraft#26]
Full length log: https://pastebin.com/xLp5hS9t
You'll notice a bunch of irrelevant stuff like cascades from frogcraft and futurepack, but i know it is from rock salt ore because i disabled your mod and things went back to normal.
the error messages went on until `MultiMC stopped watching the game log because the log length surpassed 100000 lines. You may have to fix your mods because the game is still logging to files and likely wasting harddrive space at an alarming rate!` showed up (within a few seconds - !) and i forcequit.

**Comment by Wabbit0101** [comment]
I believe this is connected to a bad oreevent from the VFP 1.8.9 port (the event is no longer valid in 1.11 forwards). This issue has been resolved in the upcoming 4.1 release (by weekend of Jan-13-2018).

**Comment by Wabbit0101** [comment]
You can disable ore generation in the meantime to verify that it is indeed the issue before I release 4.1 (see the VFP configuration gui).
