### ISSUE TITLE
BIG Buckets of liquid only make regular/buckets o' liquid if the Big Bucket is full

### ISSUE THREAD

**Issue by Gelles** [Wabbit0101/mods_hoardercraft#28]
Was making Rusty Iron Plates from Quark (eight iron ingots around a bucket of water), and noticed that I couldn't make vanilla water buckets out of my BIG Bucket of Water with 11 uses. Tried also with a Bucket o' Air with the same result.

**Comment by Gelles** [comment]
Right. Version might help. Using the 4.0 version of Super Blocks 'n Buckets on 1.12.2.

**Comment by Wabbit0101** [comment]
I can't reproduce this issue. Putting a partially filled BIG bucket with a empty bucket (either vanilla or modded) seems to produce a filled bucket and decrements the BIG bucket as expected. Can you attach your config (pastebin link is fine)?

**Comment by Gelles** [comment]
Of course.

https://pastebin.com/HDJKtphe

**Comment by Wabbit0101** [comment]
Bingo! It's something about this combination. I'll see if it's just a (fixed) Forge issue and if there's something you can do (if upgrading Forge is not an option). Older Forge and Latest Forge seem okidoki with this config file.

**Comment by Wabbit0101** [comment]
To self: After some testing, this seems to be an issue starting with Forge post 2255. The same superblocks 4.0.0 jar + shapeless wildcard recipe doesn't work for 1.12.2 even in the latest release build (2611). Works for recommended builds in 1.12 and 1.12.1. Need an isolated example to verify if SB needs new recipe or if Forge has boo-boo.

**Comment by Wabbit0101** [comment]
Temp fix in the 4.1 release. Not sure why the old wildcard recipe no longer works but for 1.13 will need changing anyways so this is ok for now.
