### ISSUE TITLE
Invisible Albino Melons?

### ISSUE THREAD

**Issue by Gelles** [Wabbit0101/mods_hoardercraft#29]
Not sure if this is an issue or not, but thought I would report it in case. 

I've been playing a world with the mod for about a day now, got myself a pen of pink sheep making that sweet sweet pink poo, and been spamming it on and off to see about getting an albino melon seed. I don't see anything, but when I clear away the grass to repoop the area (using the sickle clearing ability of Quark's hoes), I'll suddenly see grey particle effects that don't match the flowers.

So, figuring I'm just not noticing the plant, I went into creative and spammed an area. Went through about 100 poop (and more gray particles appearing) before my One Probe box popped up with "Melon Seeds" on the block I happened to be looking at.

![2018-03-06_12 09 42](https://user-images.githubusercontent.com/7891001/37049886-fd4cfbc2-2137-11e8-8b00-66a304e0534e.png)

That is very, very invisible... (that shot is without Optifine, Foamfix, or any texture packs). Is this intended behavior?

**Comment by Wabbit0101** [comment]
No. That's just the crappy Minecraft rendering of the melon stem block in gray (I reuse the vanilla block and textures, just different color given). You can actually get the same issue using just regular melon crop blocks.

I will make a note on that Special Crops page. What I do is I leave the spammed field for 1 day-night cycle which usually lets the plant grow enough so the item is rendered at stage 2 which doesn't have issues.

For a stack of poo you should get at least 2-3 plants. For 1.13, I'll probably use own textures as it's public mod now.

**Comment by Gelles** [comment]
I tried again in my survival world, without the scythe effect, and got another. Then I had the bright idea to mark the area around it with redstone and while I was doing that a little gray bit  booped up out of the ground.

Incidentally, I told my friend about this mod and her three daughters are apparently delighted by the sheer amount of poop and bugs the mod adds. :D

**Comment by Wabbit0101** [comment]
Ha! My niece when she first played, spend hours breeding cows so she could pick up the "Tiny Turds"...what will they love next...

**Comment by Wabbit0101** [comment]
This is addressed in beta 2. We reuse the vanilla texture still, but now in the first two stages of growth, the albino melon stalk will emit a full 15 levels of light making the block it's on glow like a torch. The wiki will also be updated.
