### ISSUE TITLE
Please add ability to reusable items in auto-crafter recipes

### ISSUE THREAD

**Issue by BrendanatorX** [Wabbit0101/mods_hoardercraft#32]
Not sure how best to describe this so am quoting you :P
Quote from The_Wabbit >>
The hopper doesn't know it can 'reuse' the infusion crystal. Think of the hopper as doing a craft result pickup and craft grid clear in a single operation (hence the reason it puts the remnants into the recycling slots). 
This is sortof supported with an api already present; I've just not expanded it to account for non-stackable items w/ durability automatically with a builtin adapter. If this is a feature you'd like, please open a ticket so I can review for the next release.

**Comment by Wabbit0101** [comment]
Configuration added for 4.1 release. Works assuming mod item had appropriate behavior for getContainer method.
