### ISSUE TITLE
[1.12.2] Cross mod Incompatability with Buildcraft due to error parsing it's own values 

### ISSUE THREAD

**Issue by Morpheus1101** [Wabbit0101/mods_hoardercraft#33]
https://github.com/BuildCraft/BuildCraft/issues/4098

Error log @ https://gist.github.com/Morpheus1101/893a436f791a033bd51fe2d21830bb73

**Comment by Wabbit0101** [comment]
A few quick observations(I'll investigate more later): Not sure what and especially *when* buildcraft is doing this during initialization, but re the stacktrace, vfp is not initialized properly yet (these property values are defined at the item's construction...) . Also that api (IProperty) specifies that the returned value is optional so not sure why buildcraft cannot handle null being returned. 

These storage cartons are really meant to be used as items not blocks but they shouldn't barf either. For now I'd just blacklist them as they would make horrible facades anyways :)

**Comment by Wabbit0101** [comment]
Note to self: Aha...methinks I have found the issue. These are lazy-loaded values (implementation detail) and the parseValue method is looking directly at the underlying structure w/o going through proper apis...Will be fixed in next version.

**Comment by AEnterprise** [comment]
some info on this: BC doesn't fully barf on this but this is one of the safety checks we perform on blocks and need to make facades. If a block does not accept it's own properties and returns the correct state we cannot safely save it to NBT and restore the state for rendering

whenever we enounter a block that does not parse the safety checks it gets blacklisted for the run and those errors get printed out

looking horrible is something we have not found decent checks for yet :P

**Comment by Wabbit0101** [comment]
Fixed in the 4.2 release at https://minecraft.curseforge.com/projects/vanillafoodpantry-mod/files/2568445.
