### ISSUE TITLE
Still crashing on server

### ISSUE THREAD

**Issue by Dalethium** [Wabbit0101/mods_hoardercraft#39]
[Crash log](https://pastebin.com/xxnjQwjd)

Similar to #38, client class on server.

**Comment by Wabbit0101** [comment]
Thanks for testing this; I don't have access to a 1.12 server yet. I have tried from the development IDE to ensure it at least starts up all the way through in ds mode! Can you give this a try before I post it? [pinklysheep-mc1.12-4.0b4.jar](http://jwaresoftware.org/files/mcmods/pinklysheep/mc1.12.2-4.0/pinklysheep-mc1.12-4.0b4.jar).

**Comment by Dalethium** [comment]
Hey! The server started just fine with that jar in the mods folder! Thanks so much for the fix!

**Comment by Wabbit0101** [comment]
Download now public as [4.0b4 on curseforge](https://minecraft.curseforge.com/projects/pinklysheep-mod/files/2557343). Open new issues when you discover bugs in this build. Thanks again for the reports.
