### ISSUE TITLE
[VFP] Incompatibility with BWM (Better With Mods), Can't craft Levening agent

### ISSUE THREAD

**Issue by Drakoflame** [Wabbit0101/mods_hoardercraft#42]
I'm not sure what all to write here, so i'm simply going to copy/paste the message from Curseforge that Wabbit gave me to not only give those with this issue the temporary solution until this is fixed, but also to let Wabber/Coders know the issue so they can work on it:

"The problem is that betterwithmods is removing the vanilla brown and red mushroom block definitions. When VFP tries to register its leavening ore dict keys (in this case 'additiveFermenting', 'foodMushroom', etc. for the two vanilla mushrooms), the request is rejected by Forge as invalid (which it is the itemstack is empty). The recipes all use these dict keys so they are not valid anymore. You should see ERROR messages in your Minecraft logs.

To workaround for now you can disable the betterwithmod's 'tweaks/mushroomfarming/Alias Mushrooms' config option (turn false in the GUI). I tried that and the recipes now show up fine."

 Hope this can easily be fixed soon.

**Comment by Wabbit0101** [comment]
Please check but this should be fixed in the 4.2 release. See https://minecraft.curseforge.com/projects/vanillafoodpantry-mod/files/2568445.
