### ISSUE TITLE
[1.12.1-4.1.0] Mushroom storage block easy duplication

### ISSUE THREAD

**Issue by kreezxil** [Wabbit0101/mods_hoardercraft#43]
[![Mushroom Block has no recipe](https://cdn.discordapp.com/attachments/445277549086507039/447004877709639681/unknown.png)]
Which allows it to be infinitely crafted.
All you have to do is place a recipe in any grid. The shift click the result, but keep holding shift, never release. After the initial valid recipe is done, the crafting grid will see the nothing and begin producing mushroom blocks from nothing.

Using forge build 2681

**Comment by kreezxil** [comment]
I just started using it.

**Comment by Wabbit0101** [comment]
The incompatibility will be fixed in the next VFP version. In the meantime you can disable that mod's mushroom aliasing tweak if needed. See #42

**Comment by kreezxil** [comment]
I disabled the block entirely in the config. thanks. :)

**Comment by Wabbit0101** [comment]
Please check but this should be fixed in the latest 4.2 release: https://minecraft.curseforge.com/projects/vanillafoodpantry-mod/files/2568445.
