### ISSUE TITLE
Throwing Pinkly Egg Causes Crash 

### ISSUE THREAD

**Issue by JoshD8500** [Wabbit0101/mods_hoardercraft#45]
Throwing a Pinkly egg causes the game to crash using latest version of Pinkly sheep

**Comment by Wabbit0101** [comment]
I cannot reproduce can you attach a crash report?

**Comment by Wabbit0101** [comment]
Fixed in the beta5 release at https://minecraft.curseforge.com/projects/pinklysheep-mod/files/2568543
