### ISSUE TITLE
Add Dynamic Trees Acorn Support

### ISSUE THREAD

**Issue by WrongWeekend** [Wabbit0101/mods_hoardercraft#46]
Currently the Dynamic Trees oak and dark oak acorns cannot be used in place of the VFP acorns in recipes. A simple CT script can change this but I think it makes sense to have them work without CT.

**Comment by Wabbit0101** [comment]
If you're trying to integrate unrelated mods, the CT script is better imo. Dynamic Trees seeds aren't being registered under any ore keys that I can find so interoperability would require me to put a hard link. The VFP acorn items are registered under "seedOakAcorn" in the ore dict. I'll make sure the VFP recipes use that key id if possible, but you'll have to do the integration with other mods or reach out to those mod authors.

**Comment by Wabbit0101** [comment]
Check the 4.2.1 version; it should work better with Dynamic Trees. https://minecraft.curseforge.com/projects/vanillafoodpantry-mod/files/2573538
