### ISSUE TITLE
[1.12.2] Incompatibility with Astral Sorcery 1.9.0

### ISSUE THREAD

**Issue by gchpaco** [Wabbit0101/mods_hoardercraft#47]
When trying to boot with AS 1.9.0, I got the attached traceback.  Scanning AS briefly, it appears to be calling `stack.getMaxStackSize()` on every thing in the game, and this is crashing in VFP.

[crash-2018-06-12_22.23.04-client.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/2096552/crash-2018-06-12_22.23.04-client.txt)

**Comment by Wabbit0101** [comment]
Seems to be a chisels-n-bits issue maybe as that's the mod creating the ItemStack that isn't correct (the meta is not something VFP knows about). I'll have to look at the chisels code. Thanks for the dump file as I don't use either of these mods myself.

**Comment by Wabbit0101** [comment]
This seems to be an issue with some assumptions in the chiselnbits code makes (astral sorcery is just triggering the issue w/ an attempt to use the itemstack created by chisel). The basic issue is that the item stack creation code is making as assumption about how to create a block's  item stack from a block id and the meta returned from the block's dropped item meta value. This assumption is not correct for blocks that drop items other than their own block. For cartons, the block state (meta) is NOT the same as what's dropped -- the bags. So when chiselnbits makes an item stack using the dropped item's meta against the carton's block, things go "boom" (astral sorcery is just innocently triggering the boom). Will see if I can determine a workaround.

**Comment by Wabbit0101** [comment]
Check the 4.2.1 upload; it should work better now. https://minecraft.curseforge.com/projects/vanillafoodpantry-mod/files/2573538

**Comment by jesmores** [comment]
Yup, thanks for the fix. I had the crash on boot between AS and VFP and now it's gone with the new update.
