### ISSUE TITLE
Allow VFP meat drops from animals without other drops

### ISSUE THREAD

**Issue by WrongWeekend** [Wabbit0101/mods_hoardercraft#49]
In the config file it should be possible to enable VFP meat drops from animals without enabling the other items they drop. Currently, it is only possible to enable either both or just the non-meat drops.

**Comment by Wabbit0101** [comment]
Not sure I want to add a bunch of new config options for this. If you don't want the others drops, just discard them; all of them should be pretty rare drops. I'm assuming you're talking only about items for animals that don't normally drop anything (like wolves and polar bears).

**Comment by WrongWeekend** [comment]
In particular I wanted to disable the ender pearl ingredients that squids drop (for balance purposes), but keep the meat drops.

**Comment by Wabbit0101** [comment]
Ah, Wow...you're the like only other person besides me that keeps VFP's squid meat drops :1st_place_medal: The ink pearl fragment thing I'll look at.

**Comment by Wabbit0101** [comment]
The new 4.2.1 version includes a new option to let you disable the smelting to ender pearls from ink pearls. https://minecraft.curseforge.com/projects/vanillafoodpantry-mod/files/2573538
