### ISSUE TITLE
SmartHoppers pouches incompatible with SpongeForge

### ISSUE THREAD

**Issue by jacky8399** [Wabbit0101/mods_hoardercraft#51]
Pouches work fine in singleplayer, but on a SpongeForge server, when trying to open any pouch other than the Ender Chest Pouch, the following message appears in console, and nothing is shown to the client:
`[Server thread/WARN] [net.minecraft.entity.EntityTrackerEntry]: Fetching addPacket for removed entity`

**Comment by Wabbit0101** [comment]
This is an entity spawn error message. Pouches are not entities (like animals, xp orbs, etc.) and have no entity-related functionality. You'll have to provide more information why you think this message is connected to smarthopper pouches?

**Comment by Wabbit0101** [comment]
Bump...Is there any more information you can provide? (A specific use-case as that entity error isn't pouch-related.)

**Comment by jacky8399** [comment]
Sorry for the late response. Indeed, the addPacket log is not related to the pouches. However, no error messages can be seen at the console. The server is using Forge 2705 and SpongeForge beta 3328 for 1.12.2 if it helps.

**Comment by Wabbit0101** [comment]
With 1.14 rewrite will have to see what if any SpongeForge support possible.
