### ISSUE TITLE
Request - [Upsizer mod 1.12.2] - Wildcard support!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Wabbit0101/mods_hoardercraft#59]
S:other_objects_maxstack_sizes <
        yafm: * =64
        animania: * =64
     >
*
= wildcard so it would read modid:*=stacksize

**Comment by P3rf3ctXZer0** [comment]
Greatly reduce configuration time when adding new mods

**Comment by P3rf3ctXZer0** [comment]
You could also just add global size adjustments ;D

**Comment by Wabbit0101** [comment]
Take a look at [the StackUp! mod](https://minecraft.curseforge.com/projects/stackup); it gives you this and loads more. Let me know if that helps or you'd like Upsizer feature added still. If you use StackUp just add a config file with something like: `id~="animania:*" -> 64` for each of your mods; it also has those global defaults if you prefer.

**Comment by P3rf3ctXZer0** [comment]
@Wabbit0101 I could not get that mod to work.

**Comment by Wabbit0101** [comment]
After re-reading this request, it's not likely that Upsizer will ever just blindly upsize ALL items (including blocks) that belong to a mod. The potential for rather bad things happening is huge and it's slow as it involves blindly traversing the item registry looking for things named.
