### ISSUE TITLE
Spruce Tea

### ISSUE THREAD

**Issue by WrongWeekend** [Wabbit0101/mods_hoardercraft#61]
Conifer needles, including spruce, were historically used to make tea or beer when other sources of vitamin C were unavailable. As VFP has only two types of tea currently, using spruce leaves to create a third type would be a simple way to add a bit of variety.

**Comment by Wabbit0101** [comment]
Did not know this...nice...https://www.healthygreensavvy.com/spruce-tea/. Will try to include in upcoming 1.13 version for sure. Thanks for the suggestion.

**Comment by Wabbit0101** [comment]
Done for 1.14 version.
