### ISSUE TITLE
[VFP+SuperBlocks] Ground Acorn Meal only takes Potable Water

### ISSUE THREAD

**Issue by Gelles** [Wabbit0101/mods_hoardercraft#63]
Heyo I'm back, playing my little Wabbit Season personal modpack.

As far as I've seen, Ground Acorn Meal is the only recipe that doesn't take SuperBlocks' water buckets. It only takes anything ore dict'd as "portionPotableWaterLarge,"even if TAN compatibility is turned off. This looks like just default vanilla water buckets and the VFP Potable Water.

Tested with Forge .2815, VFP 4.3.0 and SBNB 4.2.2

**Comment by Wabbit0101** [comment]
The problem is that Superblocks doesn't know you've flipped that config in VFP and conditional json-based recipes in Forge are a pain-in-the-tuckus. I have a bug fix release queued up; I'll see if I can add a fix.

**Comment by Wabbit0101** [comment]
VFP is moved to universal fluid buckets for 1.14 as has SuperBlocks so this has become a non-issue. However, we won't see anything until Forge has rewritten it's fluid system for mc-1.14 which could be some time...perhaps not before mc-1.15 :(
