### ISSUE TITLE
Raw Condensed Milk is imba

### ISSUE THREAD

**Issue by benserwa** [Wabbit0101/mods_hoardercraft#66]
Raw Condensed Milk gives you eight shanks of hunger, the most in the whole mod, and nine and a half saturation, tied for second place, plus three minutes of Speed III, for what seems like relatively little in the way of resources and effort, compared to the mod's other top performing foods.

**Comment by Wabbit0101** [comment]
It's also what you get when you simple add up what ingredients go into the item: 4x bottles of milk + 12x sugars. The food values in VFP are largely a reflection of what raw ingredient goes into the item not what 'effort' is required to obtain those items (most values are computed dynamically w/ clamps to keep within reason). If you add the lowest value (1pt) per sugar and 2pts per milk bottle the raw combined values are even larger. The speed boost is added for two reasons: 1) as stated above, you're actually losing food value by making this item and 2) seriously. why would you make this to consume directly unless you're looking for a concentrated effect of sugar.

**Comment by benserwa** [comment]
It seems to be a difference in balance philosophy then. I would argue that higher hunger restoration values should be more difficult to achieve. (I may just end up making my own food mod some day...)

**Comment by Wabbit0101** [comment]
Balance philosophy in modded minecraft is best left to the ultimate user and modpack authors (mostly...as players will subvert a pack author's wishes in a second if those wishes rub them the wrong way enough). It's virtually impossible for a single purpose mod to _enforce_ any balance based on the author's own idea of what that word implies. With that in mind, VFP is written to "fit with vanilla" with a few bonuses (which are admittedly things I and my family want to have mostly) with an eye to making sure pack authors and players can easily nuke these bonuses and recipes and recreate their own balance. You're the ultimate user here, so nuke away and craft tweak a new harder recipe or maybe edit the food values to something you prefer!

**Comment by Wabbit0101** [comment]
Values are as expected.
