### ISSUE TITLE
Squids are not dropping raw squid

### ISSUE THREAD

**Issue by kenohio** [Wabbit0101/mods_hoardercraft#71]
Possibly due to a typo in the item data?  It's currently showing as "squidd_raw".  Not sure if the extra "d" is intentional.

**Comment by Wabbit0101** [comment]
The name is correct. 

Because so many other mods add this feature, squid do not drop VFP's raw squid by default; you need to enable the option in your configs. Refer to: [VFP-MobDrops](https://github.com/Wabbit0101/mods_hoardercraft/wiki/VFP-MobDrops#squid)

**Comment by Wabbit0101** [comment]
Re-open if the config is not the cause of your problem.
