### ISSUE TITLE
Albino melons never spawning

### ISSUE THREAD

**Issue by viveleroi** [Wabbit0101/mods_hoardercraft#73]
pinklysheep-mc1.12.2-4.0

I have a custom modpack and have gone through three stacks of Pinkly Poo on minecraft grass blocks and never see an albino melon spawn. I've done so at night too, and never see any light so I'm fairly confident that I'm not missing anything.

Are there any known incompatibilities? Any other reason the spawn would never occur?

**Comment by viveleroi** [comment]
I guess I'll close this. I stubbornly went through a fourth stack and finally got one. It says "melon seeds" in the one probe, but it's glowing.

**Comment by Wabbit0101** [comment]
Sorry about that but sometimes RNG is a giant pain-in-the-bum. It should give 1-2 per stack without such bad luck. Be sure to let the seedling fully grow and generate a melon before trying to replant it.
