### ISSUE TITLE
[PinklySheep] Albino apples don't drop with Harvestcraft

### ISSUE THREAD

**Issue by Azmalent** [Wabbit0101/mods_hoardercraft#74]
What it says in the title.
Albino apples don't seem to drop at all when Harvestcraft is installed (I broke a huge amount of leaves, so I'm certain). I can confirm this happens when only these two mods are installed.

Harvestcraft is closed source so I can't know for sure, but I assume this is somehow related to fruit trees.

**Comment by JoshD8500** [comment]
Albino Apples drop from dark oak leaves using the whack-a-leaf stick

**Comment by Azmalent** [comment]
I know, that's what I used. This works only without Harvestcraft

**Comment by Wabbit0101** [comment]
This might be a problem with Harvestcraft's substitution of the vanilla apple. Pinklysheep will try to _replace_ any regular apples with albino apples if all other conditions are right. PnK doesn't actually add albino apples as a drop.

**Comment by Wabbit0101** [comment]
Try the [4.0.1 CurseForge version](https://www.curseforge.com/minecraft/mc-mods/pinklysheep-mod/files/2748241); see if you can get albino apples now.

**Comment by Azmalent** [comment]
Yes, now everything works as intended.
