### ISSUE TITLE
[PinklySheep] Special Mobs compatibility

### ISSUE THREAD

**Issue by Azmalent** [Wabbit0101/mods_hoardercraft#75]
Currently, some of PS's special drops (like silverfish dust) don't drop with Special Mobs installed, since it overrides vanilla mobs by default. 
It would be nice to add compatibility with all mob variants introduced by this mod.

**Comment by Wabbit0101** [comment]
Not sure this is message for PinklySheep to add compatibility with all mob variants or the other way around. If it's directed at PinklySheep, this mod's primary concern is tweaking vanilla mobs and that's unlikely to change in the forseeable future. (Also starting with Minecraft 1.14 players can add their own drop tweaks using a data pack that adjusts the modded mobs loot table.)
