### ISSUE TITLE
can't load mod

### ISSUE THREAD

**Issue by xile808** [Wabbit0101/mods_hoardercraft#77]
vanillafoodpantry encountered a error during load_registries

wondering why when the only mods i have are these two plus forge?

![image](https://user-images.githubusercontent.com/54512544/63655451-f8f0b300-c73c-11e9-8b70-dde1ec3c7d23.png)

**Comment by Wabbit0101** [comment]
You really need to add more information that this if you want a useful response. I have no idea what version of Forge or VFP or Minecraft you're using. Please include the proper information; I cannot help otherwise.

**Comment by Wabbit0101** [comment]
Reopen when you've added version information.

**Comment by Wabbit0101** [comment]
Self: Issue with the 1.14 early betas. Fixed in 5.0b3
