### ISSUE TITLE
Crash on startup: A superblock can only be comprised of other recognized blocks

### ISSUE THREAD

**Issue by h3oCharles** [Wabbit0101/mods_hoardercraft#78]
hi, game crashes on startup, dunno what it's caused by other than SuperBlocks erroring
here's a crash report https://pastebin.com/nr2vyHMD

EDIT: Disabling FoamFix does not help

**Comment by Wabbit0101** [comment]
This is usually caused by another mod substituting a vanilla block for its own implementation. Typical culprit is something like Quark substituting the slime block. Check https://github.com/Wabbit0101/mods_hoardercraft/issues/69#issuecomment-496300860
