### ISSUE TITLE
[1.12.2] Error executing task (modpack)

### ISSUE THREAD

**Issue by Omni35** [Wabbit0101/mods_hoardercraft#79]
So I'm playing the LITV modpack and I'm getting a lot of crashes doing various things from this mod. 
Placing a squirmies farm box dupes it with a crash report, trying to farm pinkly mycelium returns nothing but a crash report, using pinkly poo on dirt/grass gives a crash as well and glitches out giving infinite spawn on dirt after using a poop, getting a mooshroom calf crashes the game to desktop. 

[https://gist.github.com/Omni35/ccd4bf6a297cf7fe50e35c337f941a3c](url)

**Comment by Wabbit0101** [comment]
Thanks for the report. Some 1.13 code was included in backported bugfixes by mistake. Will fix shortly. You'll have to ask the modpack author to verify and update the pack when possible.

**Comment by Wabbit0101** [comment]
If you can, verify the following version resolves your issue: [4.0.2](https://www.curseforge.com/minecraft/mc-mods/pinklysheep-mod/files/2801968).
