### ISSUE TITLE
[1.14.4 ] Error when trying to play multiplayer.

### ISSUE THREAD

**Issue by Dothmar** [Wabbit0101/mods_hoardercraft#80]
When trying to join my own server I get kicked and I get this message: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.UnsupportedOperationException: Wrapping subclass MUST provide serializer getter functionality. 
I can play single player fine.

**Comment by Wabbit0101** [comment]
This will be fixed in the next beta (hopefully tomorrow oct-09-2019). Will post update when jar is uploaded.

**Comment by Wabbit0101** [comment]
New version 5.0b3 has been posted: [https://www.curseforge.com/minecraft/mc-mods/vanillafoodpantry-mod/files/2804987](https://www.curseforge.com/minecraft/mc-mods/vanillafoodpantry-mod/files/2804987). Works for dedicated servers/LAN now. Thanks for the report.
