### ISSUE TITLE
snips delete ozzy liner

### ISSUE THREAD

**Issue by Shivaxi** [Wabbit0101/mods_hoardercraft#84]
I've enabled the auto ozzy liners for my modpack RLCraft and gave them their own crafting recipe.  Normally when using the snips to take a warming or cooling liner out of armor, it gives you the liner back, however with the auto liners, it just deletes it.

**Comment by Wabbit0101** [comment]
This is working as designed as [documented here on the wiki](https://github.com/Wabbit0101/mods_hoardercraft/wiki/AUw#special-armor-liners).  This is also indicated in the liners' tooltips where it states the liners are single-install. For your modpack, it might be possible for CraftTweaker to help (though I don't know if it can detect NBT data to know when to return the liner). 

If you have suggestion for clearer tooltip text, post a new enhancement but the current behavior is working as intended.
