### ISSUE TITLE
Configs not loading AUW

### ISSUE THREAD

**Issue by CLittleLunaC** [Wabbit0101/mods_hoardercraft#85]
I am using Armor underwear 1.0.0 and TAN 3.1.0 
I do not have the configs for Armor underwear and I wanted to add the Construct's armory to the list of armors that can have the liners, but I do not have the configs the mod loads just fine, just no configs is there a quick fix? or just reinstall the mod?

**Comment by Wabbit0101** [comment]
I don't understand what you mean by "I do not have the configs"...the configs should be generated automatically by Forge if you don't have them. Are you looking for a file named 'wabbity_armorunder.cfg' in your install's config folder?

**Comment by CLittleLunaC** [comment]
Let me double check, I've had the happen before with a different mod where
forge glitched an I had to reinstall or update my forge.

**Comment by CLittleLunaC** [comment]
Alright it's there now, XD I hate my computer sometimes, I had to re
install my forge, my computer hates Minecraft for some reason so strange
problems like this arise quite often for me. I had to reinstall Minecraft
itself about 6 times before it was finally working.

**Comment by Wabbit0101** [comment]
Now that you have the config file, you can edit the '**integration**' section like so for Construct's Armory:
- Under 'S:boots' add `conarm:boots`
- Under 'S:chestplate' add `conarm:chestplate`
- Under 'S:helmet' add `conarm:helmet`
- Under 'S:leggings' add `conarm:leggings`

**Comment by CLittleLunaC** [comment]
Thanks! This makes putting in the armor a whole lot easier
