### ISSUE TITLE
[VFP] [1.12.2] TAN Compat

### ISSUE THREAD

**Issue by Remyrios** [Wabbit0101/mods_hoardercraft#88]
I really like that your mod has TAN compatibility by default.
But considering some people might want to tweak the thirst values for balance purposes or have different ways of lowering/increasing your temperature I think it would be cool to make the compat more configurable.
The least you could do would be to add config options for:
-  disabling thirst related compat
-  disabling temperature related compat

Right now, adding new drinks through TAN's .json just adds to the custom values to these from VFP.
So for example when I tweaked milk bottle to give only 2 points of thirst instead of default 4 it gave me 6 points.

**Comment by Wabbit0101** [comment]
From my perspective that would add a lot of configuration (therefore work and ongoing testing and support) for a feature that almost no one seems to care about (seriously, you're like the first person). The thirst values are based on TAN's own juices, Tea The Story's values, a few other mods, and my own pack's requirements.

I do like the idea of controlling thirst vs temp _wholesale_, but seeing as TAN is dead and unlikely to be revived (the mod authors are not even supporting the current 1.12.2 version), I'm not going to do new development for TAN. To balance your own pack, I suggest you just turn of TAN compatibility in VFP (this will wipe my values), and configure VFP items the usual way using TAN's own config system.

**Comment by Remyrios** [comment]
I understand that you don't want to change anything there as TAN is no longer maintained. I have one question tho, won't disabling the TAN compat also remove the warm and cool dishes/drinks mechanic? I don't think I could manage to do this with TAN's .json files but not 100% sure as TAN has 0 docs on the configuration files syntax.

PS. Do you have any public email address or account on Discord, so I could contact you in the future and don't make useless 1 question issues here?

**Comment by Wabbit0101** [comment]
In the 1.12 version yes it would. It disables everything TAN-related.  I did put your suggestions on my mental queue if we ever get something like TAN for Minecraft 1.14+.

For contact, you can always just PM from any of my CurseForge projects. That's like a pubilc access for private one-to-one email that I do check.
