### ISSUE TITLE
[VFP] Flesh meal does not get consumed.

### ISSUE THREAD

**Issue by Giggitybyte** [Wabbit0101/mods_hoardercraft#93]
This effects vines, sugar cane, flowers, and lily pads.
Using flesh meal on any of the above blocks _will not_ consume the flesh meal. In addition, the block will drop its item, essentially duplicating the item for free. I get the impression the item drop is intended, but flesh meal not being consumed is a bit of a problem.

Video demonstration [here](https://youtu.be/Q3tVx5sgiY8).

Forge 1.14.4-28.1.111
VFP 1.14.4-5.0b4

**Comment by Giggitybyte** [comment]
Hey, @Wabbit0101, any update on this?

**Comment by Wabbit0101** [comment]
This is fixed. It will appear in the next release.

**Comment by Wabbit0101** [comment]
Check [the latest mod download on CurseForge](https://www.curseforge.com/minecraft/mc-mods/vanillafoodpantry-mod/files/2883053).
