### ISSUE TITLE
1.15.2-badly compressed packets when joining server

### ISSUE THREAD

**Issue by SDUBZ** [Wabbit0101/mods_hoardercraft#96]
forge: 1.15.2-31.1.18
VP: vanillafoodpantry-mc1.15.2-5.5b1
http://puu.sh/FiUf6/677aedc701.png

**Comment by Wabbit0101** [comment]
I have no idea what that picture means. I can run against a forge-1.15.2-31.1.18 dedicated server fine with VFP 5.5b1. Please provide more context regarding as to why you think this is a VFP issue (like a stack trace).
