### ISSUE TITLE
[Sugestion] Special Decker Ore Dict

### ISSUE THREAD

**Issue by StellaBiscuit** [Wabbit0101/mods_hoardercraft#97]
Should make a special Ore Dict for each Decker Ingredient, NO food would have that Ore Dict by default, it would be used for modpack creator so that they can easly add ingredient (Using CraftTweaker), also, make something in the config that would make the craft unable to use the normal Ore Dict except the special one

Exemple : 

Deckers
foodDeckerBread
foodDeckerProtein
foodDeckerVegetable
foodDeckerCondiment

King-Me Decker
foodDeckerSandwitch

**Comment by StellaBiscuit** [comment]
sorry for reopening, I thought about something but realized that it wouldn't work

**Comment by Wabbit0101** [comment]
I'm assuming you're talking about the 1.12+ version of vanillafoodpantry. Read this wiki entry for Decker sandwiches; just about everything you're suggesting has a dict entry already: [Decker Overview](https://github.com/Wabbit0101/mods_hoardercraft/wiki/VFP-Sandwiches#decker-sandwiches).

**Comment by StellaBiscuit** [comment]
Ok so looks like there is a little problem, if I change some item from the foodKebabVeggie, I will change the recipe for BOTH Kebab and Decker, it's not what I want, I want separated ore dict so that I can change deckers or kebab. Also, other mod can use (accidentaly) the same ore dict, if that happen, I will change recipe I don't want to change. So adding a special ore dict with VFP in it will garentee that it will not be used by an other mod.

The issue is closed so there is a lot of change that you will not see this (sadly) but I wanted to precise more about what I wanted, sometime I can badly explain things

**Comment by Wabbit0101** [comment]
The dictionary is meant to be shared between things in precisely this way. If you want to affect a single crafted item then remove the current recipe and create a custom recipe for that item with crafttweaker or some such mod. The current ore dictid is my way of saying "if it's a cookable vegetable of the right food pt range it can go into both these crafted foods and other similar things (like a vegetable stew for instance)". I don't use public forge ore dict ids for such specific use cases. As for accidental usage -- this is basically impossible for mod-defined ids, a mod author must choose to use an ore dict explicitly (these are not forge-originated ids).
