### ISSUE TITLE
[Superblocks] Suggestion to normalize tie recipes

### ISSUE THREAD

**Issue by h3oCharles** [Wabbit0101/mods_hoardercraft#98]
for every recipe using ties, use this recipe

MMM
MTM
MMM

m - material
t - tie

and remove recipes without ties

i am well aware that i can change recipes with a mod like CraftTweaker

**Comment by Wabbit0101** [comment]
You can remove recipes without ties by turning on supercompatibility mode. The tie-based recipes are far more cumbersome and impossible from a player's grid than the other recipes and will not be set as the default. Use the option (or as you've noted CraftTweaker) to alter that default.
